(function(g){var window=this;'use strict';var $V=function(U){U.isActive()||U.start()},eX=function(U){const O={languageCode:U.languageCode,
languageName:U.languageName,displayName:g.tB(U),kind:U.kind,name:U.name,id:U.id,is_servable:U.K,is_default:U.isDefault,is_translateable:U.isTranslateable,vss_id:U.vssId};U.xtags&&(O.xtags=U.xtags);U.captionId&&(O.captionId=U.captionId);U.translationLanguage&&(O.translationLanguage=U.translationLanguage);return O},FeZ=function(U,O){const r=new g.Kj;
r.languageCode=U.languageCode;r.languageName=U.languageName;r.name=U.name;r.displayName=U.displayName;r.kind=U.kind;r.isDefault=!1;r.K=U.K;r.isTranslateable=U.isTranslateable;r.vssId=U.vssId;r.url=U.url;r.translationLanguage=O;U.xtags&&(r.xtags=U.xtags);U.captionId&&(r.captionId=U.captionId);return r},ZB=function(U,O){return O?U.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},TGL=function(U){return g.Uv(U)||U.Z("web_enable_caption_language_preference_stickiness")},KeI=async function(U,O){U=
U+"|"+O;
O=await g.Sl();if(!O)throw g.$H("gct");return(await g.rd(O)).get("captions",U)},JkI=function(U,O,r){KeI(U,O).then(V=>{V&&r(V.trackData,new g.Kj(V.metadata))})},At=function(U){if(!zvK.test(U))throw Error("'"+U+"' is not a valid hex color");
U.length==4&&(U=U.replace(M$B,"#$1$1$2$2$3$3"));U=U.toLowerCase();U=parseInt(U.slice(1),16);return[U>>16,U>>8&255,U&255]},w2K=function(){var U={};
let O="suggest_correction"in g.yF?g.yF.suggest_correction:"Edit caption";O=O||"";for(let r in U){const V=()=>String(U[r]);
O=O.replace(new RegExp("\\$\\{"+r+"\\}","gi"),V);O=O.replace(new RegExp("\\$"+r,"gi"),V)}return O},ht=function(){return g.FR("yt-player-caption-display-settings")},bv3=function(U,O){g.zv(O,r=>U.equals(r))||O.push(U)},p9=function(U,O){switch(O.kind){case "asr":bv3(O,U.U);
break;default:bv3(O,U.W)}},klk=async function(U,O,r){U.W=g.Ws(O,r)},Chg=function(U,O){let r=g.gP(U.segments,O);
r>=0||r<0&&(-r-1)%2===1||(r=-r-1,r>0&&O-U.segments[r-1]===1&&r<U.segments.length&&U.segments[r]-O===1?(g.ki(U.segments,r),g.ki(U.segments,r-1)):r>0&&O-U.segments[r-1]===1?U.segments[r-1]=O:r<U.segments.length&&U.segments[r]-O===1?U.segments[r]=O:(g.sy(U.segments,r,0,O),g.sy(U.segments,r+1,0,O)))},qe2=function(U){return U.K&&U.K.J?U.K.J+U.player.lr()<U.player.getCurrentTime():!1},vFQ=function(U,O){if(U.policy.y$&&U.player.sT()){var r=g.hF(O,U.policy,{});
r.set("pot",U.player.sT());r=r.Ti()}else r=g.hF(O,U.policy,{}).Ti();const V={format:"RAW",withCredentials:!0};if(U.policy.Vn){V.method="POST";const S=O.J;S&&Object.keys(S).length>0?V.postBody=g.VZ(S,g.p0):V.postBody=(0,g.In)([120,0])}U.X&&(V.responseType="arraybuffer");let D=++U.Fe;const m=(0,g.b)();U.W=g.hc(r,V,3,100,-1,S=>{S.errorCode==="net.timeout"&&U.player.O("capnt",{rn:D++})}).then(S=>{if(U.policy.gO&&D%100===1){var E=(0,g.b)();
U.player.O("caprsp",{rn:D,ms:E-m,kb:(S.xhr.responseText.length/1024).toFixed()})}a:{S=S.xhr;U.NQ();if(U.U){var d=!(U.X?S.response:S.responseText)||S.status>=400;if(E=g.Bg(S)){S=g.hF(U.U,U.policy,{});U.U.Pn(S,E);vFQ(U,U.U);break a}d?U.player.O("capfail",{status:S.status}):(g.I6("fcb_r",(0,g.b)(),U.player.getVideoData()?.G||""),E=U.U.MQ[0],d=E.B$,U.V!=null&&U.B!==d&&(U.X?U.V(S.response,(E.startTime+U.player.lr())*1E3):U.V(S.responseText,(E.startTime+U.player.lr())*1E3),U.B=d))}U.U=null;U.W=null}}).g2(S=>
{U.U=null;
U.W=null;U.player.O("capfail",{rn:D,status:S.xhr?.status})});
U.U=O;Chg(U.J,U.U.MQ[0].B$)},Yew=function(U,O){return O!=null&&O in U.W.K?U.W.K[O]:null},BGQ=function(U,O,r){const V=[];
for(const D in U.W.K){if(!U.W.K.hasOwnProperty(D))continue;const m=U.W.K[D];if(g.E5(m,r||null)){const S=m.info.captionTrack;S&&S.languageCode===O&&V.push(m)}}return V.length?V[0]:null},UaL=function(U,O){const r=[];
for(const D in U.W.K){if(!U.W.K.hasOwnProperty(D))continue;var V=U.W.K[D];if(g.E5(V,O||null)){let m=V.info.id,S=m,E=`.${m}`,d="",L="";if(V=V.info.captionTrack)m=V.languageCode,S=V.displayName,E=V.vssId,d=V.kind,L=V.id;else{{V=m;let u=g.CbY.get(V);u==null&&(u=stZ[V]||stZ[V.replace(/-/g,"_")],g.CbY.set(V,u));V=u}S=V||S}r.push(new g.Kj({id:D,languageCode:m,languageName:S,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:E,kind:d,captionId:L}))}}return r},f9=function(U){if(typeof DOMParser!="undefined")return g.Gr(new DOMParser,
g.yh(U),"application/xml");
throw Error("Your browser does not support loading xml documents");},OiZ=function(U,O,r,V){let D=O/360*16;
O>=U&&(U=640,V>r*1.3&&(U=480),D=r/U*16);return D},gsT=function(U){let O=1+.25*(U.fontSizeIncrement||0);
if(U.offset===0||U.offset===2)O*=.8;return O},rYM=function(U,O){let r="vertical-rl";
U.K.ME===1&&(r="vertical-lr");g.Ca&&(r=r==="vertical-lr"?"tb-lr":"tb-rl");g.PR(O,"-o-writing-mode",r);g.PR(O,"-webkit-writing-mode",r);g.PR(O,"writing-mode",r);g.PR(O,"text-orientation","upright");g.Mm(O,"ytp-vertical-caption");U.U.params.qm===3&&(g.PR(O,"text-orientation",""),g.PR(O,"transform","rotate(180deg)"))},VbL=function(U,O){const r={};
var V=O.background?O.background:U.K.R2.background;if(O.backgroundOpacity!=null||O.background){var D=O.backgroundOpacity!=null?O.backgroundOpacity:U.K.R2.backgroundOpacity;V=At(V);r.background="rgba("+V[0]+","+V[1]+","+V[2]+","+D+")";U.PE&&(r["box-decoration-break"]="clone",r["border-radius"]=`${U.sB*.375}px`)}if(O.fontSizeIncrement!=null||O.offset!=null)r["font-size"]=`${U.AQ*gsT(O)}px`;V=1;D=O.color||U.K.R2.color;if(O.color||O.textOpacity!=null)D=At(D),V=O.textOpacity==null?U.K.R2.textOpacity:O.textOpacity,
D="rgba("+D[0]+","+D[1]+","+D[2]+","+V+")",r.color=D,r.fill=D;var m=O.charEdgeStyle;m===0&&(m=void 0);if(m){D=`rgba(34, 34, 34, ${V})`;let d=`rgba(204, 204, 204, ${V})`;O.hj&&(d=D=O.hj);const L=U.AQ/16/2,u=Math.max(L,1);var S=Math.max(2*L,1),E=Math.max(3*L,1);const G=Math.max(5*L,1);V=[];switch(m){case 4:for(;E<=G;E+=L)V.push(`${S}px ${S}px ${E}px ${D}`);break;case 1:S=window.devicePixelRatio>=2?.5:1;for(m=u;m<=E;m+=S)V.push(`${m}px ${m}px ${D}`);break;case 2:V.push(`${u}px ${u}px ${d}`);V.push(`-${u}px -${u}px ${D}`);
break;case 3:for(E=0;E<5;E++)V.push(`0 0 ${S}px ${D}`)}r["text-shadow"]=V.join(", ")}D="";switch(O.fontFamily){case 1:D='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:D='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:D='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:D='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:D='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:D=g.Mr()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:D='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}D&&(r["font-family"]=D);D=O.offset;D==null&&(D=U.K.R2.offset);switch(D){case 0:r["vertical-align"]="sub";break;case 2:r["vertical-align"]="super"}O.fontFamily===7&&(r["font-variant"]="small-caps");O.bold&&(r["font-weight"]="bold");O.italic&&(r["font-style"]="italic");O.underline&&
(r["text-decoration"]="underline");O.yv&&(r.visibility="hidden");O.Ol===1&&U.X&&(r["text-combine-upright"]="all",r["text-orientation"]="mixed",D=g.mD||g.xH,U.U.params.qm===3?r.transform=D?"rotate(90deg)":"rotate(180deg)":D&&(r.transform="rotate(-90deg)"));if(O.textEmphasis===1||O.textEmphasis===2||O.textEmphasis===3||O.textEmphasis===4||O.textEmphasis===5)if(g.mD)r["font-weight"]="bold";else switch(r["text-emphasis-style"]="filled circle",r["text-emphasis-color"]="currentcolor",r["webkit-text-emphasis"]=
"filled circle",O.textEmphasis){case 4:case 3:r["text-emphasis-position"]="under left";r["webkit-text-emphasis-position"]="under left";break;case 5:case 2:r["text-emphasis-position"]="over right",r["webkit-text-emphasis-position"]="over right"}return r},QH=function(U){U=U.split("px");
return U.length>0?(U=Number(U[0]))?U:0:0},S9k=function(U,O,r){U.qQ=U.qQ||!!r;
const V={};Object.assign(V,U.K.R2);Object.assign(V,r||O.K);Object.assign(V,U.cE.R2);(r=!U.G)&&DaM(U);let D=U.f7&&U.lk&&g.IV(V,U.lk)?U.f7:mai(U,V);const m=typeof O.text==="string",S=m?O.text.split("\n"):[O.text];for(let d=0;d<S.length;d++){var E=d>0||!O.append;const L=S[d];E&&!r?(DaM(U),D=mai(U,V)):E&&r&&(r=!1);L&&(D.appendChild(m?g.DA(L):L),m||L.tagName!=="RUBY"||L.childElementCount!==4||g.mD||!g.ZE(L.children[2],"text-emphasis")||(E=U.X?"padding-right":"padding-top",g.ZE(L.children[2],"text-emphasis-position")&&
(E=U.X?"padding-left":"padding-bottom"),g.vt?g.PR(D,E,"1em"):g.PR(D,E,"0.5em")))}U.lk=V;U.f7=D;U.V.push(O)},DaM=function(U){U.G=g.VD("SPAN");
g.PR(U.G,{display:"block"});g.Mm(U.G,"caption-visual-line");U.B.appendChild(U.G)},mai=function(U,O){const r=g.VD("SPAN");
g.PR(r,{display:"inline-block","white-space":"pre-wrap"});g.PR(r,VbL(U,O));r.classList.add("ytp-caption-segment");U.G.appendChild(r);r.previousElementSibling&&(g.PR(r.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.PR(r,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return r},daY=function(U,O,r){if(U===255&&O===255||!U&&!O)return{Ma:U,
Fw:O,result:0};U=EsB[U];O=EsB[O];if(U&128){var V;if(V=!(O&128))V=O,V=r.Bt()&&r.Fw===V;if(V)return{Ma:U,Fw:O,result:1}}else if(O&128&&1<=U&&U<=31)return{Ma:U,Fw:O,result:2};return{Ma:U,Fw:O,result:3}},uQL=function(U,O,r,V){O===255&&r===255||!O&&!r?(++U.U===45&&U.reset(),U.J.W.clear(),U.X.W.clear()):(U.U=0,Lyw(U.J,O,r,V))},GKY=function(U,O){U.K.sort((r,V)=>{const D=r.time-V.time;
return D===0?r.order-V.order:D});
for(const r of U.K)U.time=r.time,r.type===0?uQL(U,r.vv,r.Jc,O):r.type===1&&U.W&496&&Lyw(U.X,r.vv,r.Jc,O);U.K.length=0},tbB=function(U,O){switch(U){case 0:return Hii[(O&127)-32];
case 1:return lPI[O&15];case 2:return j1w[O&31];case 3:return iiZ[O&31]}return 0},yH=function(U,O){if(U.style.type===3){var r=0,V=0,D=U.X.time+0,m="",S="",E=D;
for(var d=1;d<=15;++d){var L=!1;for(var u=V?V:1;u<=32;++u){var G=U.U[d][u];if(G.K!==0){r===0&&(r=d,V=u);L=String.fromCharCode(G.K);var H=G.timestamp;H<D&&(D=H);G.timestamp=E;S&&(m+=S,S="");m+=L;L=!0}if((G.K===0||u===32)&&L){S="\n";break}else if(V&&!L)break}if(r&&!L)break}m&&O.J(r,V,D,E,m)}else for(V=r=0,m=D=U.X.time+0,S=1;S<=15;++S)for(E="",d=1;d<=32;++d)if(u=U.U[S][d],G=u.K,G!==0&&(r===0&&(r=S,V=d),L=String.fromCharCode(G),H=u.timestamp,H<=D&&(D=H),E+=L,u.reset()),d===32||G===0)E&&O.J(r,V,D,m,E),
D=m,E="",V=r=0},n9=function(U){return U.U[U.row][U.W]},N0=function(U,O,r){O>=2&&U.W>1&&(--U.W,n9(U).K=0);
const V=n9(U);V.timestamp=U.X.time+0;V.K=tbB(O,r);U.W<32&&U.W++},Wy3=function(U,O,r,V){for(let S=0;S<V;S++)for(let E=0;E<=32;E++){var D=U.U[O+S][E],m=U.U[r+S][E];
D.K=m.K;D.timestamp=m.timestamp}},Id=function(U,O,r){for(let V=0;V<r;V++)for(let D=0;D<=32;D++)U.U[O+V][D].reset()},ad=function(U){U.row=U.K>0?U.K:1;
U.W=1;Id(U,0,15)},R9Y=function(U){U.style.set(1);
U.K=U.J;U.K.K=0;U.K.style=U.style;U.U.mode=1<<U.K.J},od=function(U,O,r){const V=U.W;
let D=!1;switch(U.style.get()){case 4:case 1:case 2:U.style.get()===4&&V.K>0||(yH(V,r),ad(U.W),ad(U.J),V.row=15,V.K=O,D=!0)}U.style.set(3);U.K=V;U.K.style=U.style;U.U.mode=1<<V.J;D?V.W=1:V.K!==O&&(V.K>O?(yH(V,r),Id(V,V.row-V.K,O)):V.row<O&&(O=V.K),V.K=O)},xaw=function(U){U.style.set(4);
U.K=U.text;U.K.style=U.style;U.U.mode=1<<U.K.J},Lyw=function(U,O,r,V){U.W.update();
O=daY(O,r,U.W);switch(O.result){case 0:return;case 1:case 2:return}var D=O.Ma;O=O.Fw;if(32<=D||!D)U.K.mode&U.K.W&&(r=D,r&128&&(r=127),O&128&&(O=127),U=U.J.K,r&96&&N0(U,0,r),O&96&&N0(U,0,O),r!==0&&O!==0&&U.style.type===3&&yH(U,V));else if(D&16)a:if(!U.W.matches(D,O)&&(r=U.W,r.Ma=D,r.Fw=O,r.state=2,r=D&8?U.B:U.U,U.J=r,U.K.mode=1<<(U.X<<2)+(r.X<<1)+(r.style.type===4?1:0),(U.K.mode|1<<(U.X<<2)+(r.X<<1)+(r.style.type!==4?1:0))&U.K.W))if(O&64){V=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(D&7)<<1|O>>5&1];
U=O&16?((O&14)>>1)*4:0;O=r.K;switch(r.style.get()){case 4:V=O.row;break;case 3:if(V!==O.row){if(V<O.K&&(V=O.K,V===O.row))break;var m=1+O.row-O.K;const S=1+V-O.K;Wy3(O,S,m,O.K);r=m;D=O.K;S<m?(m=S+D-m,m>0&&(r+=m,D-=m)):(m=m+D-S,m>0&&(D-=m));Id(O,r,D)}}O.row=V;O.W=U+1}else switch(D&7){case 1:switch(O&112){case 32:N0(r.K,0,32);break a;case 48:O===57?(V=r.K,n9(V).K=0,V.W<32&&V.W++):N0(r.K,1,O&15)}break;case 2:O&32&&N0(r.K,2,O&31);break;case 3:O&32&&N0(r.K,3,O&31);break;case 4:case 5:if(32<=O&&O<=47)switch(O){case 32:R9Y(r);
break;case 33:V=r.K;V.W>1&&(--V.W,n9(V).K=0);break;case 36:V=r.K;U=n9(V);for(O=0;O<=15;O++)for(r=0;r<=32;r++)if(V.U[O][r]===U){for(;r<=32;r++)V.U[O][r].reset();break}break;case 37:od(r,2,V);break;case 38:od(r,3,V);break;case 39:od(r,4,V);break;case 40:N0(r.K,0,32);break;case 41:V=r;V.style.set(2);V.K=V.W;V.K.K=0;V.K.style=V.style;V.U.mode=1<<V.K.J;break;case 42:V=r;U=V.text;U.K=15;U.style.set(4);ad(U);xaw(V);break;case 43:xaw(r);break;case 44:U=r;O=U.W;switch(U.style.get()){case 1:case 2:case 3:yH(O,
V)}Id(O,0,15);break;case 45:b:{O=r;U=O.K;switch(O.style.get()){default:case 2:case 1:break b;case 4:if(U.row<15){++U.row;U.W=1;break b}break;case 3:}U.K<2&&(U.K=2,U.row<U.K&&(U.row=U.K));O=U.row-U.K+1;yH(U,V);Wy3(U,O,O+1,U.K-1);Id(U,U.row,1)}break;case 46:Id(r.J,0,15);break;case 47:U=r,yH(U.W,V),U.J.updateTime(U.U.time+0),V=U.J,U.J=U.W,U.W=V,R9Y(U)}break;case 7:switch(O){case 33:case 34:case 35:V=r.K,(V.W+=O&3)>32&&(V.W=32)}}},cY2=function(U,O,r,V,D,m,S){var E=m[0];
let d=S[E.getAttribute("p")];if(d.uA===1){var L=m[1],u=m[2];m=m[3];E.getAttribute("t");L.getAttribute("t");u.getAttribute("t");m.getAttribute("t");E.getAttribute("p");L.getAttribute("p");m.getAttribute("p");S=S[u.getAttribute("p")];E=Pmi(E.textContent,L.textContent,u.textContent,m.textContent,S);return new XM(U,O,D,r,E,V,d)}switch(d.uA){case 9:case 10:d.textEmphasis=1;break;case 11:d.textEmphasis=2;break;case 12:d.textEmphasis=3;break;case 13:d.textEmphasis=4;break;case 14:d.textEmphasis=5}return new XM(U,
O,D,r,E.textContent||"",V,d)},Pmi=function(U,O,r,V,D){var m=g.Mr();
const S=m?g.VD("DIV"):g.VD("RUBY"),E=g.VD("SPAN");E.textContent=U;S.appendChild(E);U=m?g.VD("DIV"):g.VD("RP");U.textContent=O;S.appendChild(U);O=m?g.VD("DIV"):g.VD("RT");O.textContent=r;S.appendChild(O);r=D.uA;if(r===10||r===11||r===12||r===13||r===14)if(g.PR(O,"text-emphasis-style","filled circle"),g.PR(O,"text-emphasis-color","currentcolor"),g.PR(O,"webkit-text-emphasis","filled circle"),D.uA===11||D.uA===13)g.PR(O,"webkit-text-emphasis-position","under left"),g.PR(O,"text-emphasis-position","under left");
r=!0;if(D.uA===4||D.uA===7||D.uA===12||D.uA===14)g.PR(S,"ruby-position","over"),g.PR(S,"-webkit-ruby-position","before");else if(D.uA===5||D.uA===6||D.uA===11||D.uA===13)g.PR(S,"ruby-position","under"),g.PR(S,"-webkit-ruby-position","after"),r=!1;D=m?g.VD("DIV"):g.VD("RP");D.textContent=V;S.appendChild(D);m&&(V=r,g.PR(S,{display:"inline-block",position:"relative"}),m=S.firstElementChild.nextElementSibling,g.PR(m,"display","none"),m=m.nextElementSibling,g.PR(m,{"font-size":"0.5em","line-height":"1.2em",
"text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.PR(S.lastElementChild,"display","none"),V?(g.PR(S,"padding-top","0.6em"),g.PR(m,"top","0")):(g.PR(S,"padding-bottom","0.6em"),g.PR(m,"bottom","0")));return S},$aM=function(U){const O="_"+FM++;
return new Tq(0,0x8000000000000,0,O,U)},K9=function(U,O){U=U.getAttribute(O);
if(U!=null)return Number(U)},Jt=function(U,O){U=U.getAttribute(O);
if(U!=null)return U==="1"},zq=function(U,O){U=K9(U,O);
return U!==void 0?U:null},wk=function(U,O){U=U.getAttribute(O);
if(U!=null)return M0.test(U),U},e9Y=function(U,O){const r={},V=O.getAttribute("ws");
Object.assign(r,V?U.G[V]:U.J);U=zq(O,"mh");U!=null&&(r.Dq=U);U=zq(O,"ju");U!=null&&(r.textAlign=U);U=zq(O,"pd");U!=null&&(r.qm=U);U=zq(O,"sd");U!=null&&(r.ME=U);U=wk(O,"wfc");U!=null&&(r.windowColor=U);O=K9(O,"wfo");O!==void 0&&(r.windowOpacity=O/255);return r},ZiZ=function(U,O){const r={},V=O.getAttribute("wp");
V&&Object.assign(r,U.V[V]);U=zq(O,"ap");U!=null&&(r.Nc=U);U=K9(O,"cc");U!=null&&(r.T5=U);U=K9(O,"ah");U!=null&&(r.xz=U);U=K9(O,"rc");U!=null&&(r.l3=U);O=K9(O,"av");O!=null&&(r.kQ=O);return r},AYZ=function(U,O,r,V){let D={};
Object.assign(D,ZiZ(U,O));Object.assign(D,e9Y(U,O));V?g.IV(D,U.J)?(V=U.X,D=U.J):V="_"+FM++:V=O.getAttribute("id")||"_"+FM++;U=K9(O,"t")+r;O=K9(O,"d")||0x8000000000000;if(D.qm===2||D.qm===3)r=D.l3,D.l3=D.T5,D.T5=r;return new Tq(U,O,0,V,D)},bc=function(U){U=g.u4(Math.round(U),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-U.length)+U},h9K=function(U,O,r,V,D){V===0&&(V=0x8000000000000);
const m={};O.wpWinPosId&&Object.assign(m,U.J.get(O.wpWinPosId));O.wsWinStyleId&&Object.assign(m,U.X.get(O.wsWinStyleId));U=O.rcRowCount;U!==void 0&&(m.l3=U);O=O.ccColCount;O!==void 0&&(m.T5=O);if(m.qm===2||m.qm===3)O=m.l3,m.l3=m.T5,m.T5=O;return new Tq(r,V,0,D,m)},kV=function(U){const O=U.byteOffset;
U.byteOffset+=1;return U.K.getUint8(O)},C9=function(U){const O=U.byteOffset;
U.byteOffset+=4;return U.K.getUint32(O)},Q1i=function(U){if(typeof U==="string")return!1;
U=new pCk(U,0);return fPQ(U)},fPQ=function(U){if(!(U.byteOffset<U.K.byteLength)||C9(U)!==1380139777)return!1;
U.version=kV(U);if(U.version>1)return!1;kV(U);kV(U);kV(U);return!0},yYg=function(U,O){if(!O)return"";
U.X&&U.U.params.ME!==1&&(O*=-1);return`translate${U.X?"X":"Y"}(${O}px)`},nsk=function(U){U.m3=Array.from(U.element.getElementsByClassName("caption-visual-line"));
for(var O=U.U.params.l3,r=0,V=0,D=U.m3.length-1;r<O&&D>-1;){var m=U.m3[D];V+=U.X?m.offsetWidth:m.offsetHeight;r++;D--}U.Fe=V;O=Math;r=O.max;isNaN(U.Vn)&&((V=U.K.T5)?(D=g.VD("SPAN"),g.L3(D,"\u2013".repeat(V)),g.PR(D,VbL(U,U.K.R2)),U.B.appendChild(D),U.Vn=D.offsetWidth,U.B.removeChild(D)):U.Vn=0);V=U.B;U.W$=r.call(O,U.Vn,U.TN,(U.X?V.offsetHeight:V.offsetWidth)+1)},NLY=function(U,O){nsk(U);
var r=U.m3.reduce((V,D)=>(U.X?D.offsetWidth:D.offsetHeight)+V,0);
r=U.Fe-r;if(r!==U.tQ){const V=r>0&&U.tQ===0,D=r<U.tQ;O||isNaN(r)||V||!D||(g.Mm(U.element,"ytp-rollup-mode"),U.K7(U.element,"transitionend",U.c$));g.PR(U.B,"transform",yYg(U,r));U.tQ=r}nsk(U)},aPw=function(U,O,r,V){const {formatId:D,
B$:m,startTimeMs:S,durationMs:E}=U.X(O),d={formatId:D,startTimeMs:S,durationMs:E,Ks:m,Zc:m};let L=IPK(U.Ky,d.startTimeMs);const u=L>=0?U.Ky[L]:null,G=u?u.startTimeMs+u.durationMs:0,H=d.startTimeMs+d.durationMs;!u||d.startTimeMs-G>U.J?U.Ky.splice(L+1,0,d):(u.durationMs=Math.max(G,H)-u.startTimeMs,u.Zc=Math.max(u.Zc,d.Zc));V(U.Ky);V=g.bw(O);U=U.B;V=V.buffer.slice(V.byteOffset,V.byteLength+V.byteOffset);O=O.info.U;U.A?U.V==null?g.JF(U.logger,350058965,"Null loaded track meta data at captions data received"):
r.df(V,U.V,O*1E3):g.JF(U.logger,350058965,"Null Representation at captions data received")},FyL=function(U,O){U.W=(r,V)=>{if(U.C.S().experiments.yn("html5_sabr_live_support_subfragmented_captions"))(U.K?U.K=U.K.X(r):(U.K=r,osw(U.K)),U.K)?r.info.Bh&&(XCT(U.K),aPw(U,U.K,O,V),U.K=null):g.JF(U.logger,350058965,"Empty slice");
else if(r.info.Bh){var D=r;if(U.J2.length>0){for(D=U.J2.shift();U.J2.length>0;)D=D.X(U.J2.shift());D=D.X(r)}D?(osw(D),XCT(D),aPw(U,D,O,V)):g.JF(U.logger,350058965,"Empty slice")}else U.J2.push(r)};
U.C.addEventListener("sabrCaptionsDataLoaded",U.W)},IPK=function(U,O){U=g.gP(U,{startTimeMs:O},(r,V)=>r.startTimeMs-V.startTimeMs);
return U>=0?U:-U-2},osw=function(U){let O;
try{O=g.vA(U)*1E3}catch(r){O=U.info.startTime*1E3}O<0&&(O=U.info.startTime*1E3);U.info.startTime=O/1E3;U.info.U=O/1E3},XCT=function(U){let O;
try{O=g.gR(U)*1E3}catch(r){O=U.info.duration*1E3}O<0&&(O=U.info.duration*1E3);U.info.duration=O/1E3;U.info.N=O/1E3},TLi=function(U,O){if(!g.A$(U)||U.K!=null&&g.SQ(O,U.K)&&U.K.K.rawcc!=null)return!1;
O=!!U.K&&U.K.isManifestless&&Object.values(U.K.K).some(r=>g.E5(r,"386"));
U=!!U.K&&!U.K.isManifestless&&g.th(U.K);return O||U},KyM=function(U,O,r){const V=[];
for(const D in U.W.K){if(!U.W.K.hasOwnProperty(D))continue;const m=U.W.K[D];if(g.E5(m,r||null)){const S=m.info.captionTrack;S&&S.languageCode===O&&V.push(m)}}return V.length?V[0]:null},JYk=function(U,O){const r=[];
for(const D in U.W.K){if(!U.W.K.hasOwnProperty(D))continue;var V=U.W.K[D];if(g.E5(V,O||null)){let m=V.info.id,S=m,E=`.${m}`,d="",L="";if(V=V.info.captionTrack)m=V.languageCode,S=V.displayName,E=V.vssId,d=V.kind,L=V.id;r.push(new g.Kj({id:D,languageCode:m,languageName:S,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:E,kind:d,captionId:L}))}}return r},Mbi=function(U){const O=z9L.length;
if(U.byteLength<O)return!1;U=new Uint8Array(U,0,O);for(let r=0;r<O;r++)if(z9L[r]!==U[r])return!1;return!0},q0=function(U){U=U.split(":");
let O=0;for(const r of U)O=O*60+Number(r);return O*1E3},wCw=function(U,O,r,V){V=Object.assign({Dq:0},V);
return new Tq(U,O,r,"_"+FM++,V)},bii=function(U,O,r,V,D,m,S,E,d){switch(S.tagName){case "b":E.bold=!0;
break;case "i":E.italic=!0;break;case "u":E.underline=!0}for(let u=0;u<S.childNodes.length;u++){var L=S.childNodes[u];if(L.nodeType===3)L=new XM(O,r,V,D.id,L.nodeValue,m||u>0,g.yy(E)?void 0:E),d.push(L),D.K.push(L);else{const G={};Object.assign(G,E);bii(U,O,r,V,D,!0,L,G,d)}}},Cm2=function(U,O,r){if(typeof O==="string"||Q1i(O))return[{trackData:O,
tO:r}];if(typeof O==="string"&&O.substring(0,6)==="WEBVTT"||typeof O!=="string"&&Mbi(O))return[{trackData:O,tO:r}];const V=new DataView(O);if(V.byteLength<=8||V.getUint32(4)!==1718909296)return[];var D=g.cM(V);if(U.VW&&D){var m=g.Vo(D),S=g.Dc(D);D=D.segmentNumber;m&&D&&U.VW.nE(D,m,S)}U=g.RH(V,1835295092);if(!U||!U.length||!U[0].size)return[];m=[];for(S=0;S<U.length;S++)D=U[S],D=new Uint8Array(O,D.dataOffset,D.size-(D.dataOffset-D.offset)),D=g.FB(D),m.push({trackData:D,tO:r+S*1E3});kKZ(V,m,r);return m=
m.filter(E=>!!E.trackData)},vs3=function(U,O,r){U.K||(U.K=new q9g);
U=U.K.U(O,r);Math.random()<.01&&g.H9(Error("Deprecated subtitles format in web player: WebVTT"));return U},kKZ=function(U,O,r){var V=g.ul(U,0,1836476516);
let D=9E4;V&&(D=g.ll(V)||9E4);V=0;const m=g.RH(U,1836019558);for(let E=0;E<m.length;E++){var S=m[E];E<O.length&&(S=g.ul(U,S.dataOffset,1953653094))&&(S=g.ul(U,S.dataOffset,1952867444))&&(S=g.t6(S)/D*1E3,E===0&&(V=S),O[E].tO=S-V+r||r*E*1E3)}},Y9T=function(U){const O={};
if(U=g.Wu(U))O.lang=U,g.YGK.test(U)&&(O.qm=1);return O},BLB=function(U){const O=!!U.C.dL()?.Vn();
return U.U==="HLS"&&O?!0:U.lk&&O&&U.U!=="LIVE"&&U.U!=="SABR_LIVE"},v8=function(U,O,r=!1){var V=U.D.Z("enable_player_captions_new_style_defaults")?s1M:Ue3;
const D=V.R2;U.X={};Object.assign(U.X,V);U.X.R2={};Object.assign(U.X.R2,D);U.B={R2:{}};var m=O.backgroundOverride?U.B:U.X,S=O.background||D.background;M0.test(S);m.R2.background=S;m=O.colorOverride?U.B:U.X;S=O.color||D.color;M0.test(S);m.R2.color=S;m=O.windowColorOverride?U.B:U.X;S=O.windowColor||V.windowColor;M0.test(S);m.windowColor=S;m=O.backgroundOpacityOverride?U.B:U.X;S=O.backgroundOpacity;S==null&&(S=D.backgroundOpacity);m.R2.backgroundOpacity=S;m=O.fontSizeIncrementOverride?U.B:U.X;S=O.fontSizeIncrement;
S==null&&(S=D.fontSizeIncrement);m.R2.fontSizeIncrement=S;S=O.fontStyleOverride?U.B:U.X;m=O.fontStyle;m==null&&(m=D.bold&&D.italic?3:D.bold?1:D.italic?2:0);S=S.R2;switch(m){case 1:S.bold=!0;delete S.italic;break;case 2:delete S.bold;S.italic=!0;break;case 3:S.bold=!0;S.italic=!0;break;default:delete S.bold,delete S.italic}m=O.textOpacityOverride?U.B:U.X;S=O.textOpacity;S==null&&(S=D.textOpacity);m.R2.textOpacity=S;m=O.windowOpacityOverride?U.B:U.X;S=O.windowOpacity;S==null&&(S=V.windowOpacity);m.windowOpacity=
S;V=O.charEdgeStyleOverride?U.B:U.X;m=O.charEdgeStyle;m==null&&(m=D.charEdgeStyle);V.R2.charEdgeStyle=m;V=O.fontFamilyOverride?U.B:U.X;m=O.fontFamily;m==null&&(m=D.fontFamily);V.R2.fontFamily=m;U.loaded&&U.sB();r&&g.or("yt-player-caption-display-settings",O,2592E3)},YV=function(U,O,r){O&&!U.Y?(O=$aM({qm:0,
lang:"en"}),U.Y=[O,new XM(O.start,O.end-O.start,0,O.id,r??"Captions look like this")],U.player.H6(U.Y)):!O&&U.Y&&(ODZ(U,U.Y),U.Y=null)},geL=function(U){if(!U.C.isInline())return g.FR("yt-player-sticky-caption")},B8=function(U){if(!U.D.Z("enable_player_captions_persistence_state_machine")){var O=void 0,r=g.wq().L7(65);
if(g.Uv(U.D)&&r!=null){if(geL(U)!=null)return!1;O=!r}return O}},ru2=function(U){if(U.D.y6===1||U.videoData.Jn===1||g.lu(U.videoData,"yt:cc")==="alwayson")return!0;
let O;U.videoData.captionTracks.length&&(O=U.getAudioTrack().W);if(U.D.Z("enable_player_captions_persistence_state_machine")){var r=U.D.Z("enable_player_captions_persistence_state_machine")?g.FR("yt-player-caption-persistence"):void 0;if(r!==void 0)return!!r}else if(U.D.y6===2){if(g.Uv(U.D))r=geL(U);else if(U.storage)try{r=U.storage.get("module-enabled")}catch(D){U.storage.remove("module-enabled")}else r=null;if(r!=null)return!!r}r=ZB(U.player.getAudioTrack(),g.Uv(U.D));const V=g.lu(U.videoData,"yt:cc");
if(B8(U)===void 0){if(r==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return V?V==="on":!0;if(r==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return V==="on"}else return V==="on";return O==="ON"||g.lu(U.videoData,"yt:cc")==="on"},sr=function(U,O=!1){if(U.W&&!O||!U.videoData.captionTracks.length)return!1;
U=U.getAudioTrack();return!!U.K||U.W==="FORCED_ON"},VMZ=function(U){return U.D.Z("html5_honor_caption_availabilities_in_audio_track")&&U.U!=="LIVE"&&U.U!=="SABR_LIVE"},Dek=function(U,O){if(U.W){var r=U.C.dL().Ed().textTracks,V=null;
U.U==="HLS"?V=U.W.getId():V=U.W.toString();for(let m=0;m<r.length;m++){var D=r[m];D.id===V&&(O?D.mode!=="showing"&&(D.mode="showing",D=U.W,U.kF(D,!!D,Un(U)?"g":U.V?"m":"s")):D.mode==="showing"&&(D.mode="disabled"))}}},Un=function(U){const O=On(U);
return!!O&&U.W===O},mei=function(U,O){if(U.U==="HLS")return!1;
g.co(U.videoData)&&(O=!0);O||(O=U.U==="TTS"?!1:U.U==="INNERTUBE"?!1:!0);return O||U.D.Z("web_watch_disable_account_level_captions_settings")&&g.Uv(U.D)?!0:!!g.wq().L7(66)},On=function(U){return U.G&&U.G.K},gU=function(U,O){if(!U.K)return null;
if(U.G&&U.G.J)return U.G.J;O=mei(U,O);O=U.K.K.K(O);let r=null;if(TGL(U.D)){var V=U.C.isInline()?void 0:g.FR("yt-player-caption-sticky-language");var D=[V,U.videoData.captionsLanguagePreference,U.D.captionsLanguagePreference,g.lu(U.videoData,"yt:cc_default_lang")];let E=!1;for(let d=0;d<D.length;d++){const L=D[d];if(L){E=!0;for(var m=0;m<O.length;m++)if(g.Wu(O[m])===L)return O[m];for(m=0;m<O.length;m++)if(g.Wu(O[m]).split("-")[0]===L.split("-")[0])return O[m]}}if(E&&U.K&&(D=U.K.G,D.length))for(var S of D)if(S.languageCode===
V){r=S;break}}else for(S=[U.videoData.captionsLanguagePreference,U.D.captionsLanguagePreference,g.lu(U.videoData,"yt:cc_default_lang")],V=0;V<S.length;V++)for(D=0;D<O.length;D++)if(g.Wu(O[D])===S[V])return O[D];S=null;U.G&&U.G.U&&(S=U.G.U);S||(S=O.find(E=>E.isDefault)||null);
S||(S=O[0]||On(U));S&&r&&g.Wu(S).split("-")[0]!==r.languageCode.split("-")[0]&&(S=FeZ(S,r));return S},ST=function(U,O,r){U.loaded&&U.unload();
r!=null&&(U.V=r,U.V&&(U.D.Z("enable_player_captions_persistence_state_machine")?rU(U,!!O):g.Uv(U.D)?VG(U,!!O):Dm(U,!!O)));O!==null||sr(U,!0)||U.kF(O,!!O,U.V?"m":"s");U.W=O;sr(U)&&(U.W=On(U));mQ(U,U.W??void 0);U.load()},rU=function(U,O){U.D.Z("enable_player_captions_persistence_state_machine")&&g.or("yt-player-caption-persistence",O,3122064E3)},VG=function(U,O){U.C.isInline()||g.or("yt-player-sticky-caption",O,2592E3)},Dm=function(U,O){if(U.storage)try{U.storage.set("module-enabled",O)}catch(r){}},
mQ=function(U,O){U.D.Z("html5_modify_caption_vss_logging")&&(U.videoData.MZ=O)},Eew=function(U,O){var r=U.Fe[O.id];
r&&r.U!==O&&(r.dispose(),delete U.Fe[O.id],r=null);r||(r=StQ(U,O))&&(U.Fe[O.id]=r)},deZ=function(U,O){const r=O.windowId;
U.OB[r]||(U.OB[r]=[]);U.OB[r].push(O)},StQ=function(U,O){const r=LdZ(U);
if(!r)return null;var V=U.W?g.Wu(U.W):null;V&&g.YGK.test(V)&&(O.params.qm=1);var D=U.TH.getPlayerSize();V=D.height*U.A.height;D=D.width*U.A.width;U.D.playerStyle!=="google-live"||U.X.isDefault||Object.assign(O.params,U.X);switch(O.params.Dq!=null?O.params.Dq:O.K.length>1?1:0){case 1:return new uHQ(O,U.X,U.B,r.width,r.height,D,V,U.D.experiments,U.AQ.bind(U),U.C);case 2:return new GII(O,U.X,U.B,r.width,r.height,D,V,U.D.experiments,U.AQ.bind(U),U.C);default:return new En(O,U.X,U.B,r.width,r.height,D,
V,U.D.experiments,U.AQ.bind(U),U.C)}},LdZ=function(U){let O=U.TH.getVideoContentRect(!0).height,r=U.TH.getVideoContentRect(!0).width;
if(!O||!r)return null;O*=U.A.height;r*=U.A.width;return{width:r,height:O}},ODZ=function(U,O){U.player.uc(O);
for(const r of O)g.Cu(U.m3,r);$V(U.Vn)},HDL=function(U,O){if(!U.K)return{};
if(O){g.yy(O)||U.ev(O.vss_id,"m");if(U.J&&U.U!=="HLS"||!g.Zg(O))return;if(g.yy(O)){ST(U,null,!0);return}let V;var r=U.K.K.K(!0);for(let D=0;D<r.length;D++){const m=r[D];m.languageCode!==O.languageCode||V&&(m.languageName!==O.languageName||(m.captionId||"")!==(O.captionId||"")||g.tB(m)!==O.displayName)||(V=O.translationLanguage?FeZ(m,O.translationLanguage):m)}U.i8(O.position);!V||V===U.W&&U.loaded||(O=g.qU(),r=g.Wu(V),O.length&&r===O[O.length-1]||(O.push(r),g.or("yt-player-caption-language-preferences",
O)),TGL(U.D)&&!U.C.isInline()&&g.or("yt-player-caption-sticky-language",r,2592E3),ST(U,V,!0))}else return U.loaded&&U.W&&!Un(U)?eX(U.W):{};return""};
g.a1.prototype.nE=g.V3(119,function(U,O,r){this.W.set(U,{Ww:O,xT:r})});
g.o1.prototype.nE=g.V3(118,function(U,O,r){this.W$.nE(U,O,r)});
g.Te.prototype.G=g.V3(117,function(){this.mediaElement.G()});
g.a8.prototype.G=g.V3(116,function(){var U=g.b4(document,"track",void 0,this.K);for(let O=0;O<U.length;O++)g.Ec(U[O])});
g.Te.prototype.qQ=g.V3(115,function(){return this.mediaElement.qQ()});
g.a8.prototype.qQ=g.V3(114,function(){return!(!this.K.textTracks||!this.K.textTracks.addEventListener)});
g.Te.prototype.Vn=g.V3(113,function(){return this.mediaElement.Vn()});
g.a8.prototype.Vn=g.V3(112,function(){return!!this.K.textTracks});
g.Te.prototype.Fe=g.V3(111,function(U){this.mediaElement.Fe(U)});
g.a8.prototype.Fe=g.V3(110,function(U){for(let O=0;O<U.length;O++)this.K.appendChild(U[O])});
g.dL.prototype.ev=g.V3(46,function(U,O){this.app.H$().ev(U,O)});
g.d0.prototype.ev=g.V3(45,function(U,O){this.j.ev(U,O)});
g.$s.prototype.ev=g.V3(44,function(U,O){U=[U,O];g.BH(this,g.US(this.provider),"cfi",U)});
g.hY.prototype.ev=g.V3(43,function(U,O){this.qoe&&this.qoe.ev(U,O)});
g.iC.prototype.ev=g.V3(42,function(U,O){this.GH.ev(U,O)});
g.ni.prototype.ev=g.V3(41,function(){});
g.dL.prototype.kF=g.V3(40,function(U,O,r){this.app.H$().kF(U,O,r)});
g.d0.prototype.kF=g.V3(39,function(U,O,r){this.j.kF(U,O,r)});
g.$s.prototype.kF=g.V3(38,function(U,O,r){if(this.SJ!==U||this.BE!==O)O=O==="rawcc"?"":O,r=[U,O,this.SJ,r],g.BH(this,g.US(this.provider),"cfs",r),this.SJ=U,this.BE=O});
g.hY.prototype.kF=g.V3(37,function(U,O,r){this.qoe&&this.qoe.kF(U,O,r)});
g.iC.prototype.kF=g.V3(36,function(U,O,r){this.GH.kF(U,O,r)});
g.ni.prototype.kF=g.V3(35,function(){});
g.hJ.prototype.Zh=g.V3(9,function(){return this.VW});
g.TK.prototype.Zh=g.V3(8,function(){return this.H$().PB()});
g.dL.prototype.PB=g.V3(7,function(){return this.app.Zh()});
g.d0.prototype.PB=g.V3(6,function(){return this.j.PB()});
g.iC.prototype.PB=g.V3(5,function(){return this.loader?.Zh()||null});
g.ni.prototype.PB=g.V3(4,function(){return null});
g.v2.prototype.Yh=g.V3(2,function(U){return(U=this.U(U))?U.K:0});
g.B2.prototype.Yh=g.V3(1,function(){return 0});
var M$B=/#(.)(.)(.)/,zvK=/^#(?:[0-9a-f]{3}){1,2}$/i,stZ={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Arab:"Kazakh (Arabic)",kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",ku_Latn:"Kurdish (Latin)",kum:"Kumyk",kut:"Kutenai",kv:"Komi",
kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",
maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",
mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",
nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pms:"Piedmontese",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",
pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",
sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",
sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelauan",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",
tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",
vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",
zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"},lGi=class{constructor(){this.U=[];this.W=[]}K(U){return U?this.W.concat(this.U):this.W}},dU=class extends g.f{constructor(U){super();this.Qn=U;this.K=new lGi;this.W$=new lGi;this.X=null;this.G=[];this.Fe=[]}N(){}J(){}U(){}B(){return""}Xe(){return!1}kz(U,O){if(this.Qn.S().Z("html5_dispatch_tracklist_loaded_event")){this.X&&(this.X.reject(),this.X=null);var r=[];this.Qn.hQ("trackListLoaded",
this.K,r,O);this.Qn.S().Z("enable_po_decoration_of_forced_tracks")&&this.Qn.hQ("trackListLoaded",this.W$,r,O);r.length?(O=new g.b9,O.promise.then(U.kz,()=>{}),this.X=O,Promise.all(r).then(O.resolve,O.reject).finally(()=>{this.X=null})):U.kz()}else U.kz()}UB(){this.X&&(this.X.reject(),this.X=null);
this.U();super.UB()}},j4B={en:"English"},iDT=class extends dU{constructor(U){super(U);this.W=new Set}J(U){var O=this.Qn.dL();if(O&&O.Ed()){O=O.Ed().textTracks;for(const r of O)r.kind==="subtitles"&&!this.W.has(r.language)&&r.language&&(p9(this.K,new g.Kj({languageCode:r.language,languageName:r.language,kind:r.kind,id:r.id,displayName:j4B[r.label]||r.label,vss_id:`.${r.language}`})),this.W.add(r.language))}this.K.K().length>0&&U.kz()}},tML=class extends dU{constructor(U,O,r){super(U);this.videoData=
O;this.audioTrack=r;this.W=null;this.V=!1;this.G=O.HF;this.Fe=O.pS;this.V=g.co(O)}N(U,O,r){this.NQ();O=this.B(U,O);const V=this.Qn.S().Z("html5_report_captions_ctmp_qoe"),D=(0,g.b)();this.U();klk(this,O,{format:"RAW",onSuccess:m=>{this.W=null;if(V){var S=(m.responseText.length/1024).toFixed();const E=(0,g.b)();this.videoData.O("capresp",{ms:E-D,kb:S})}S=m.getResponseHeader&&m.getResponseHeader("Content-Length")?Number(m.getResponseHeader("Content-Length")):0;r.df(m.responseText,U,void 0,void 0,S)},
onError:V?m=>{this.videoData.O("capfail",{status:m?.status??0})}:void 0,
withCredentials:!0})}J(U){if(this.audioTrack){for(const O of this.audioTrack.captionTracks)p9(this.K,O);this.audioTrack.K&&p9(this.W$,this.audioTrack.K)}this.kz(U,this.videoData.videoId)}B(U,O){const r=U.Ti(),V={fmt:O};if(O==="srv3"||O==="3"||O==="json3")g.Mr()?Object.assign(V,{xorb:2,xobt:1,xovt:1}):Object.assign(V,{xorb:2,xobt:3,xovt:3});U.translationLanguage&&(V.tlang=g.Wu(U));this.V&&(V.xosf="1");Object.assign(V,this.Qn.S().K);return g.qY(r,V)}U(){this.W&&this.W.abort()}},Wdw=class{constructor(){this.segments=
[]}contains(U){U=g.gP(this.segments,U);return U>=0||U<0&&(-U-1)%2===1}length(){return this.segments.length/2}},RNk=class extends g.f{constructor(U,O,r,V,D,m){super();this.policy=U;this.player=O;this.Te=r;this.V=V;this.X=D;this.A=m;this.J=new Wdw;this.B=-1;this.W=this.U=this.K=null;this.Fe=0;this.N=new g.Xq(this.G,1E3,this);this.events=new g.se(this);g.Q(this,this.N);g.Q(this,this.events);this.events.K7(O,"SEEK_COMPLETE",this.Y);this.Y();this.G()}UB(){super.UB();this.W&&this.W.cancel()}Y(){this.seekTo(this.player.getCurrentTime())}seekTo(U){U-=
this.player.lr();const O=this.K;this.K=g.If(this.Te.B(U).MQ);O!==this.K&&this.A&&this.A()}reset(){this.J=new Wdw;this.B=-1;this.W&&(this.W.cancel(),this.W=null)}G(){this.NQ();var U;if(U=this.K!=null)U=this.K,U=U.Te.J(U);if(U&&!this.W&&!(this.K&&this.K.startTime-this.player.getCurrentTime()>30)){U=this.K;U=U.Te.Vn(U);const D=U.MQ[0];if(this.player.getVideoData()?.enableServerStitchedDai){var O=this.player.PB();if(O){var r=D.Te.info.id;const m=D.B$;var V=U.MQ[0].U;if(this.policy.Vn){if(O=g.S4(O,V,m,
r,3))U.J=O}else if(r=O.Eg(V,m,r,3))if(V=2,O.GG.has(m)?V=0:g.Eo(O,m)&&(V=1),O=V,O===0)r&&(U.K=new g.J0(r));else if(O===2){this.N.start();qe2(this)&&this.seekTo(this.player.getCurrentTime());return}}}D.Te.index.YQ(D.B$)?(this.J.contains(U.MQ[0].B$)||vFQ(this,U),this.K=g.If(U.MQ)):qe2(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()}},xeM=class extends dU{constructor(U,O){super(O);this.W=U;this.C=O;this.V=null;this.Y=!1;this.logger=new g.Kr("caps");this.A=g.SQ(this.C,this.W)}N(U,O,r){this.U();
O=Yew(this,U.getId());O||(O=U.languageCode,O=this.W.isManifestless?BGQ(this,O,"386"):BGQ(this,O));if(O){var V=(O.index.Yh(O.index.OT())-O.index.getStartTime(O.index.OT()))*1E3,D=new g.UWL(this.C.S());this.V=new RNk(D,this.C,O,(m,S)=>{r.df(m,U,S,V)},this.A||g.wX(O.info),()=>{this.V&&this.V.reset();
this.Y=!0})}}Xe(){const U=this.Y;
this.Y=!1;return U}J(U){var O=this.C.S().Z("html5_fallback_if_rawcc_missing");const r=this.W.K.rawcc!=null;if(!this.A||!r&&O)O=this.W.isManifestless?UaL(this,"386"):UaL(this);else{if(!r){g.JF(this.logger,386248249,"rawcc used but unavailable");return}O=[new g.Kj({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Kj({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(const V of O)p9(this.K,
V);U.kz()}U(){this.V&&(this.V.dispose(),this.V=null)}B(){return""}},P0Y=class extends dU{constructor(U,O,r,V,D,m){super(U);this.videoId=r;this.Y=D;this.eventId=m;this.A={};this.W=null;U=V||g.kB(O).hl||"";U=U.split("_").join("-");this.V=g.qY(O,{hl:U})}N(U,O,r){this.NQ();O=this.B(U,O);this.U();this.W=g.Ws(O,{format:"RAW",onSuccess:V=>{this.W=null;const D=V.getResponseHeader&&V.getResponseHeader("Content-Length")?Number(V.getResponseHeader("Content-Length")):0;r.df(V.responseText,U,void 0,void 0,D)},
withCredentials:!0})}J(U){let O=this.V;const r={type:"list",tlangs:1,v:this.videoId,vssids:1};this.Y&&(r.asrs=1);O=g.qY(O,r);this.U();this.W=g.Ws(O,{format:"RAW",onSuccess:V=>{this.W=null;if((V=V.responseXML)&&V.firstChild){var D=V.getElementsByTagName("track");for(var m=0;m<D.length;m++){var S=D[m],E=S.getAttribute("lang_code");const d=S.getAttribute("lang_translated"),L=S.getAttribute("name"),u=S.getAttribute("kind"),G=S.getAttribute("id"),H=S.getAttribute("lang_default")==="true",l=S.getAttribute("cantran")===
"true";S=S.getAttribute("vss_id");p9(this.K,new g.Kj({languageCode:E,languageName:d,name:L,kind:u,id:G,is_servable:!0,is_translateable:l,vss_id:S,is_default:H}))}V=V.getElementsByTagName("target");D=V.length;for(m=0;m<D;m++)E={languageCode:V[m].getAttribute("lang_code"),languageName:V[m].getAttribute("lang_translated"),languageOriginal:V[m].getAttribute("lang_original"),id:V[m].getAttribute("id"),isDefault:V[m].getAttribute("lang_default")==="true"},this.A[E.languageCode]=E.languageName,this.G.push(E)}this.kz(U,
this.videoId)},
withCredentials:!0})}B(U,O){let r=this.V;O={v:this.videoId,type:"track",lang:U.languageCode,name:U.getName(),kind:U.kind,fmt:O};const V=this.Qn.S();V.Z("captions_url_add_ei")&&(O.ei=this.eventId);U.translationLanguage&&(O.tlang=g.Wu(U));Object.assign(O,V.K);return r=g.qY(r,O)}U(){this.W&&this.W.abort()}},M0=/^#(?:[0-9a-f]{3}){1,2}$/i;var cuZ=["left","right","center","justify"];var En=class extends g.fG{constructor(U,O,r,V,D,m,S,E,d,L){const u=L.isInline()&&!0,G={};Object.assign(G,O);Object.assign(G,U.params);Object.assign(G,r);const H={};Object.assign(H,O.R2);U.params.R2&&Object.assign(H,U.params.R2);Object.assign(H,r.R2);u&&(G.windowOpacity=.6,H.backgroundOpacity=0);G.R2=H;const l=G.qm===1,P=[{L:"span",p7:"captions-text",xX:{style:"word-wrap: normal; display: block;"}}],h=E.yn("caption_edit_on_hover")&&L.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
h&&P.unshift({L:"button",p7:"caption-edit",xX:{tabindex:"0","aria-label":w2K()},JQ:[{L:"svg",xX:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},JQ:[{L:"path",xX:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({L:"div",p7:"caption-window",xX:{id:`caption-window-${U.id}`,dir:l?"rtl":"ltr",tabindex:"0",lang:G.lang},JQ:P});
this.V=[];this.qQ=!1;this.U=U;this.lk=this.f7=null;this.vY=m;this.Yy=S;this.G=null;this.maxWidth=m*.96;this.maxHeight=S*.96;this.K=G;this.cE=r;this.Xe=O;this.B=this.EB("captions-text");U=this.B.style;this.PE=E.yn("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in U||"WebkitBoxDecorationBreak"in U);this.AQ=OiZ(V,D,m,S);this.A9=d;h&&(this.N=this.EB("caption-edit"),this.K7(this.N,"click",()=>{this.A9()}));
this.type=0;this.sB=this.AQ*gsT(H);this.t$=u;this.If=E.yn("enable_centered_caption_for_tvfilm_video")&&L.getVideoData().isTvfilmVideo;this.A=L.S().C7().K.L7(g.vhk);V=new g.fi(this.element,!0);g.Q(this,V);V.subscribe("dragstart",this.eT,this);V.subscribe("dragmove",this.Cc,this);V.subscribe("dragend",this.tW,this);this.xl=this.dH=this.jg=this.aS=0;V="";this.K.windowOpacity&&(V=At(this.K.windowColor),V="rgba("+V[0]+","+V[1]+","+V[2]+","+this.K.windowOpacity+")");D={"background-color":V,display:this.K.isVisible===
!1?"none":"","text-align":cuZ[this.K.textAlign]};this.PE&&(D["border-radius"]=V?`${this.sB*.375}px`:"");(this.X=this.U.params.qm===2||this.U.params.qm===3)&&rYM(this,this.element);g.PR(this.element,D);u&&this.element.parentElement?.style.setProperty("--caption-window-color",V);switch(this.K.Nc){case 0:case 1:case 2:g.Mm(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Mm(this.element,"ytp-caption-window-bottom")}}eT(U,O){this.dH=U;this.xl=O;const r=g.QW(this.element,this.element.parentElement);
this.aS=U-r.x;this.jg=O-r.y}Cc(U,O){if(U!==this.dH||O!==this.xl){g.zD(this.element,"ytp-dragging")||g.Mm(this.element,"ytp-dragging");var r=g.Iu(this.element);U=U-this.aS-.02*this.vY;var V=O-this.jg-.02*this.Yy,D=(U+r.width/2)/this.maxWidth*3;D=Math.floor(g.u4(D,0,2));var m=(V+r.height/2)/this.maxHeight*3;m=Math.floor(g.u4(m,0,2));O=D+m*3;U=(U+D/2*r.width)/this.maxWidth;U=g.u4(U,0,1)*100;r=(V+m/2*r.height)/this.maxHeight;r=g.u4(r,0,1)*100;this.U.params.Nc=O;this.U.params.kQ=r;this.U.params.xz=U;this.U.params.isDefault=
!1;this.K.Nc=O;this.K.kQ=r;this.K.xz=U;this.K.isDefault=!1;this.Xe.Nc=O;this.Xe.kQ=r;this.Xe.xz=U;this.Xe.isDefault=!1;this.Z$()}}tW(){g.b5(this.element,"ytp-dragging")}Z$(){this.Y(this.V)}Y(U){var O=this.t$?0:Math.min(this.sF(),this.maxWidth),r=this.Sg(),V=this.t$;if(V){var D=getComputedStyle(this.B.parentNode);D=QH(D.borderLeftWidth)+QH(D.borderRightWidth)+QH(D.paddingLeft)+QH(D.paddingRight)}else D=0;const m=D;D="";this.U.params.qm===3&&(D="rotate(180deg)");var S=V?`calc(96% - ${m}px)`:"96%";g.PR(this.element,
{top:0,left:0,right:"",bottom:"",width:O?`${O}px`:"",height:r?`${r}px`:"","max-width":S,"max-height":S,margin:"",transform:""});this.SJ(U);D={transform:D,top:"",left:"",width:O?`${O}px`:"",height:r?`${r}px`:"","max-width":"","max-height":""};S=this.K.Nc;var E=this.K.xz;const d=this.K.kQ;this.If&&S!=null&&(E=50,S=Math.floor(S/3)*3+1);E=E*.96+2;switch(S){case 0:case 3:case 6:(V=this.K.R2.fontSizeIncrement)&&V>0&&this.K.qm!==2&&this.K.qm!==3&&(E=Math.max(E/(1+V*2),2));D.left=`${E}%`;break;case 1:case 4:case 7:D.left=
`${E}%`;E=0;this.A||(E=this.B.offsetWidth);O||E?(O=O||E+1,D.width=`${O}px`,D["margin-left"]=V?`${O/-2-m/2}px`:`${O/-2}px`):(this.A&&(D.width="max-content"),D.transform+=" translateX(-50%)");break;case 2:case 5:case 8:D.right=`${100-E}%`}V=d*.96+2;switch(S){case 0:case 1:case 2:D.top=`${V}%`;break;case 3:case 4:case 5:D.top=`${V}%`;V=0;this.A||(V=this.element.clientHeight);(r=r||V)?(D.height=`${r}px`,D["margin-top"]=`${r/-2}px`):D.transform+=" translateY(-50%)";break;case 6:case 7:case 8:D.bottom=
`${100-V}%`}g.PR(this.element,D);if(this.N){if(this.A)r=this.sB;else{if(this.If&&U.length===0)U=0;else{r=1;for(V=0;V<U.length;V++)D=U[V],typeof D.text==="string"&&(r+=D.text.split("\n").length-1,D.append||V===0||r++);U=r}r=this.If?U>0?this.B.offsetHeight/U:0:this.B.offsetHeight/U}this.N.style.height=`${r}px`;this.N.style.width=`${r}px`;this.element.style.paddingLeft=`${r+5}px`;this.element.style.paddingRight=`${r+5}px`;this.A||(U=Number(this.element.style.marginLeft.replace("px",""))-r-5,r=Number(this.element.style.marginRight.replace("px",
""))-r-5,this.element.style.marginLeft=`${U}px`,this.element.style.marginRight=`${r}px`)}}SJ(U){let O;for(O=0;O<U.length&&U[O]===this.V[O];O++);if(this.qQ||this.V.length>O)O=0,this.qQ=!1,this.V=[],this.G=this.lk=this.f7=null,g.mR(this.B);for(;O<U.length;O++)S9k(this,U[O])}sF(){return 0}Sg(){return 0}toString(){return super.toString()}};var eNY=class{constructor(){this.U=this.time=this.mode=this.W=0;this.J=new $ei(this);this.X=new $ei(this);this.K=[];this.clear()}clear(){this.U=this.time=this.mode=0;this.K=[];this.reset()}reset(){this.mode=0;this.J.reset(0);this.X.reset(1)}},EsB=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],ZDQ=class{constructor(){this.type=0}set(U){this.type=U}get(){return this.type}},AuT=class{constructor(){this.state=this.Fw=this.Ma=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}Bt(){return this.state!==0}matches(U,O){return this.Bt()&&U===this.Ma&&O===this.Fw}},hNY=class{constructor(){this.timestamp=this.K=0}reset(){this.timestamp=
this.K=0}},Ls=class{constructor(U){this.X=U;this.U=[];this.K=this.W=this.row=0;this.style=new ZDQ;this.J=0;for(U=0;U<=15;U++){this.U[U]=[];for(let O=0;O<=32;O++)this.U[U][O]=new hNY}}updateTime(U){for(let O=1;O<=15;++O)for(let r=1;r<=32;++r)this.U[O][r].timestamp=U}debugString(){let U="\n";for(let O=1;O<=15;++O){for(let r=1;r<=32;++r){const V=this.U[O][r];U=V.K===0?U+"_":U+String.fromCharCode(V.K)}U+="\n"}return U}reset(U){for(let O=0;O<=15;O++)for(let r=0;r<=32;r++)this.U[O][r].reset();this.J=U;
this.K=0;this.W=this.row=1}},Hii=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],lPI=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],j1w=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,
194,199,200,202,203,235,206,207,239,212,217,249,219,171,187],iiZ=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],pcM=class{constructor(U){this.U=U;this.X=0;this.style=new ZDQ;this.B=new Ls(this.U);this.N=new Ls(this.U);this.text=new Ls(this.U);this.W=this.B;this.J=this.N;this.K=this.W}reset(U,O){this.X=O;this.style.set(2);this.W=this.B;this.J=this.N;this.K=this.W;const r=(U<<2)+(O<<1);this.B.reset(r);this.N.reset(r);
this.text.reset((U<<2)+(O<<1)+1)}},$ei=class{constructor(U){this.K=U;this.X=0;this.U=new pcM(this.K);this.B=new pcM(this.K);this.W=new AuT;this.J=this.U}reset(U){this.X=U;this.W.clear();this.J=this.U;this.U.reset(U,0);this.B.reset(U,1)}};var fGT=class{J(){}};var XM=class extends g.XP{constructor(U,O,r,V,D,m=!1,S=null){super(U,U+O,{priority:r,namespace:"captions"});this.windowId=V;this.text=D;this.append=m;this.K=S}toString(){return super.toString()}};var uI=class extends g.f{reset(){}};var Tq=class extends g.XP{constructor(U,O,r,V,D){super(U,U+O,{priority:r,namespace:"captions"});this.id=V;this.params=D;this.K=[]}toString(){return super.toString()}},FM=0;var Q4M=class extends uI{constructor(U){super();this.J=U;this.pens={};this.V={};this.G={};this.X="_"+FM++;this.N={};this.W=this.K=null;this.B=!0}reset(){this.N={};this.W=this.K=null;this.B=!0}U(U,O){U=U.firstChild;U.getAttribute("format");O=O||0;Number.isFinite(O);U=Array.from(U.childNodes);for(var r of U)if(r.nodeType===1)switch(r.tagName){case "head":var V=r;break;case "body":var D=r}if(V){V=Array.from(V.childNodes);for(var m of V)if(m.nodeType===1)switch(m.tagName){case "pen":r=m.getAttribute("id");
V=this.pens;U={};var S=m.getAttribute("p");S&&Object.assign(U,this.pens[S]);S=Jt(m,"b");S!=null&&(U.bold=S);S=Jt(m,"i");S!=null&&(U.italic=S);S=Jt(m,"u");S!=null&&(U.underline=S);S=zq(m,"et");S!=null&&(U.charEdgeStyle=S);S=zq(m,"of");S!=null&&(U.offset=S);S=wk(m,"bc");S!=null&&(U.background=S);S=wk(m,"ec");S!=null&&(U.hj=S);S=wk(m,"fc");S!=null&&(U.color=S);S=zq(m,"fs");S!=null&&S!==0&&(U.fontFamily=S);S=K9(m,"sz");S!==void 0&&(U.fontSizeIncrement=S/100-1);S=K9(m,"bo");S!==void 0&&(U.backgroundOpacity=
S/255);S=K9(m,"fo");S!==void 0&&(U.textOpacity=S/255);S=zq(m,"rb");S!=null&&S!==10&&S!==0&&(U.uA=S>10?S-1:S);S=zq(m,"hg");S!=null&&(U.Ol=S);V[r]=U;break;case "ws":V=m.getAttribute("id");this.G[V]=e9Y(this,m);break;case "wp":V=m.getAttribute("id"),this.V[V]=ZiZ(this,m)}}if(D){m=[];D=Array.from(D.childNodes);for(h of D)if(h.nodeType===1)switch(h.tagName){case "w":this.K=AYZ(this,h,O,!1);(D=this.N[this.K.id])&&D.end>this.K.start&&(D.end=this.K.start);this.N[this.K.id]=this.K;m.push(this.K);break;case "p":var E=
h;U=O;D=[];V=E.getAttribute("w")||this.X;r=!!Jt(E,"a");U=(K9(E,"t")||0)+U;S=K9(E,"d")||5E3;r||(!this.B&&this.W&&this.W.windowId===V&&this.W.end>U&&(this.W.end=U),this.W&&this.W.text==="\n"&&(this.W.text=""));const n=r?6:5;var d=E.getAttribute("p");d=d?this.pens[d]:null;const a=Array.from(E.childNodes);a.length&&(this.B=E.getAttribute("d")!=null);for(E=0;E<a.length;E++){var L=a[E],u=void 0;E>0&&(r=!0);let X;L.nodeType===1&&(X=L);if(X&&X.tagName==="s"){if((L=(L=X.getAttribute("p"))?this.pens[L]:null)&&
L.uA&&(L.uA===1?(L=a.slice(E,E+4),L.length===4&&(u=cY2(U,S,V,r,n,L,this.pens),E+=3)):u=cY2(U,S,V,r,n,[X],this.pens)),!u){var G=X;u=U;L=S;var H=V,l=r;const T=G.textContent?G.textContent:"";var P=G.getAttribute("p");P=P?this.pens[P]:null;G=K9(G,"t")||0;u=new XM(u+G,L-G,n,H,T,l,P)}}else u=new XM(U,S,n,V,L.textContent||"",r,d);D.push(u);this.W=u}if(D.length>0){D[0].windowId===this.X&&(this.K=AYZ(this,h,O,!0),m.push(this.K));for(const X of D)X.windowId=this.K.id,this.K.K.push(X),m.push(X)}}var h=m}else h=
[];return h}};var yuw=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),neT=class extends uI{constructor(U){super();this.B=U;this.K=new Map;this.J=new Map;this.X=new Map;this.W=new Map}reset(){this.W.clear()}U(U,O){U=JSON.parse(U);if(!U)return[];if(U.pens){var r=U.pens,V=0;for(var D of r){r={};var m=D.pParentId;m&&Object.assign(r,this.K.get(m));D.bAttr&&(r.bold=!0);D.iAttr&&(r.italic=!0);D.uAttr&&(r.underline=!0);m=D.ofOffset;m!=null&&(r.offset=m);D.szPenSize!==void 0&&(r.fontSizeIncrement=D.szPenSize/100-1);
m=D.etEdgeType;m!=null&&(r.charEdgeStyle=m);D.ecEdgeColor!==void 0&&(r.hj=bc(D.ecEdgeColor));m=D.fsFontStyle;m!=null&&m!==0&&(r.fontFamily=m);D.fcForeColor!==void 0&&(r.color=bc(D.fcForeColor));D.foForeAlpha!==void 0&&(r.textOpacity=D.foForeAlpha/255);D.bcBackColor!==void 0&&(r.background=bc(D.bcBackColor));D.boBackAlpha!==void 0&&(r.backgroundOpacity=D.boBackAlpha/255);(m=D.rbRuby)&&m!==10&&(r.uA=m>10?m-1:m,r.textEmphasis=yuw.get(r.uA));D.hgHorizGroup&&(r.Ol=D.hgHorizGroup);this.K.set(V++,r)}}if(U.wsWinStyles){V=
U.wsWinStyles;D=0;for(var S of V)V={},(r=S.wsParentId)?Object.assign(V,this.X.get(r)):Object.assign(V,this.B),S.mhModeHint!==void 0&&(V.Dq=S.mhModeHint),S.juJustifCode!==void 0&&(V.textAlign=S.juJustifCode),S.pdPrintDir!==void 0&&(V.qm=S.pdPrintDir),S.sdScrollDir!==void 0&&(V.ME=S.sdScrollDir),S.wfcWinFillColor!==void 0&&(V.windowColor=bc(S.wfcWinFillColor)),S.wfoWinFillAlpha!==void 0&&(V.windowOpacity=S.wfoWinFillAlpha/255),this.X.set(D++,V)}if(U.wpWinPositions){D=U.wpWinPositions;S=0;for(var E of D)D=
{},(V=E.wpParentId)&&Object.assign(D,this.J.get(V)),E.ahHorPos!==void 0&&(D.xz=E.ahHorPos),E.apPoint!==void 0&&(D.Nc=E.apPoint),E.avVerPos!==void 0&&(D.kQ=E.avVerPos),E.ccCols!==void 0&&(D.T5=E.ccCols),E.rcRows!==void 0&&(D.l3=E.rcRows),this.J.set(S++,D)}if(U.events){U=U.events;E=[];for(const J of U)if(S=(J.tStartMs||0)+O,D=J.dDurationMs||0,J.id)V=String(J.id),U=h9K(this,J,S,D,V),E.push(U),this.W.set(V,U);else{J.wWinId?V=J.wWinId.toString():(V="_"+FM++,U=h9K(this,J,S,D,V),E.push(U),this.W.set(V,U));
U=E;var d=J;D===0&&(D=5E3);r=this.W.get(V);const Oi=(m=!!d.aAppend)?6:5,HB=d.segs;let dM=null;d.pPenId&&(dM=this.K.get(d.pPenId));for(d=0;d<HB.length;d++){var L=HB[d],u=L.utf8;if(u){var G=L.tOffsetMs||0;let $K=null;L.pPenId&&($K=this.K.get(L.pPenId));if((r.params.Dq!=null?r.params.Dq:r.K.length>1?1:0)===2&&m&&u==="\n")continue;L=null;var H=[],l;if(l=$K&&$K.uA===1)a:{l=HB;var P=d;if(P+3>=l.length||!l[P+1].pPenId||!l[P+2].pPenId||!l[P+3].pPenId){l=!1;break a}var h=l[P+1].pPenId;(h=this.K.get(h))&&h.uA&&
h.uA===2?(h=l[P+2].pPenId,h=this.K.get(h),!h||!h.uA||h.uA<3?l=!1:(h=l[P+3].pPenId,l=(h=this.K.get(h))&&h.uA&&h.uA===2?!0:!1)):l=!1}if(l)G=HB[d+1].utf8,L=HB[d+3].utf8,l=HB[d+2].utf8,P=this.K.get(HB[d+2].pPenId),u=Pmi(u,G,l,L,P),L=new XM(S,D,Oi,V,u,m,$K),d+=3;else{if(u.indexOf("<")>-1){H=$K;l=dM;P=S;h=D;var n=G,a=Oi,X=m;const vB=[];var T=f9(`<html>${u}</html>`);if(!T.getElementsByTagName("parsererror").length&&T.firstChild?.childNodes.length)for(const Jw of T.firstChild.childNodes){T=Jw.textContent?.replace(/\n/g,
"")??"";if(Jw.nodeType===3&&(!T||T.match(/^ *$/)!=null))continue;const dP={};Object.assign(dP,H||l);switch(Jw?.tagName){case "b":dP.bold=!0;break;case "i":dP.italic=!0;break;case "u":dP.underline=!0}vB.push(new XM(P+n,h-n,a,r.id,T,X,dP))}H=vB}H.length||(H=[new XM(S+G,D-G,Oi,r.id,u,m,$K||dM)])}if(H.length)for(const vB of H)U.push(vB),r.K.push(vB);else L&&(U.push(L),r.K.push(L))}m=!0}}O=E}else O=[];return O}};var NrL=class extends dU{constructor(U,O,r){super(U);this.videoData=O;this.audioTrack=r;this.G=O.HF}N(U,O,r){JkI(this.videoData.videoId,U.vssId,r.df)}J(U){if(this.audioTrack)for(const O of this.audioTrack.captionTracks)p9(this.K,O);U.kz()}};var uHQ=class extends En{constructor(U,O,r,V,D,m,S,E,d,L){super(U,O,r,V,D,m,S,E,d,L);this.type=1}SJ(U){const O=this.U.K;super.SJ(U);let r,V;for(U=U.length;U<O.length;U++){const D=O[U];let m;V&&D.K===r?m=V:(m={},Object.assign(m,D.K),Object.assign(m,IGi),r=D.K,V=m);S9k(this,D,m)}}},IGi={yv:!0};var pCk=class extends fGT{constructor(U,O){super();this.trackData=U;this.B=O;this.version=this.X=this.U=this.byteOffset=0;this.W=[];this.K=new DataView(this.trackData)}J(U,O,r,V,D){if(r<V){const m="_"+FM++;r=r/1E3-this.B;V=V/1E3-this.B;U=new Tq(r,V-r,5,m,{textAlign:0,Nc:0,xz:O*2.5,kQ:U*5.33});D=new XM(r,V-r,5,m,D);this.W.push(U);this.W.push(D)}}},aGg=class extends uI{constructor(U,O){super();this.W=U;this.J=O;this.track=this.J.languageName==="CC3"?4:0;this.K=new eNY;this.K.W=1<<this.track}U(U){U=
new pCk(U,this.W);if(fPQ(U)){for(;U.byteOffset<U.K.byteLength;)for(U.version===0?U.U=C9(U)*(1E3/45):U.version===1&&(U.U=C9(U)*4294967296+C9(U)),U.X=kV(U);U.X>0;U.X--){var O=kV(U);const r=kV(U),V=kV(U);O&4&&(O&3)===this.track&&(this.track===0||this.track===1)&&(O=this.K,O.K.push({time:U.U,type:this.track,vv:r,Jc:V,order:O.K.length}))}GKY(this.K,U);return U.W}return[]}reset(){this.K.clear()}};var GII=class extends En{constructor(U,O,r,V,D,m,S,E,d,L){super(U,O,r,V,D,m,S,E,d,L);this.type=2;this.m3=[];this.W$=this.Fe=this.tQ=0;this.Vn=NaN;this.TN=0;this.HE=null;this.Ly=new g.Xq(this.c$,433,this);this.N&&(L.createClientVe(this.N,this,167342),this.K7(this.N,"click",()=>{L.logClick(this.N)}),U=new g.fi(this.element,!0),g.Q(this,U),U.subscribe("hoverstart",()=>{L.logVisibility(this.N,!0)},this));
g.Mm(this.element,"ytp-caption-window-rollup");g.Q(this,this.Ly);g.PR(this.element,"overflow","hidden")}Z$(){var U=this.Ly;U.stop();U.Zw()}c$(){this.element.removeEventListener("transitionend",this.c$,!1);g.b5(this.element,"ytp-rollup-mode");this.Y(this.HE,!0)}Sg(){return this.X?this.W$:this.Fe}sF(){return this.X?this.Fe:this.W$}Y(U,O){this.HE=U;if(this.U.params.l3){var r=0;for(let V=0;V<this.V.length&&r<U.length;V++)this.V[V]===U[r]&&r++;r>0&&r<U.length&&(U=this.V.concat(U.slice(r)));this.TN=this.W$;
this.Fe=this.W$=0;super.Y(U);NLY(this,O)}super.Y(U)}};var XcQ=class{constructor(U,O,r,V){this.C=U;this.B=O;this.logger=r;this.oS=V;this.Ky=[];this.K=null;this.U=[];this.J2=[];this.W=null;U=g.uo(this.C.S().experiments,"html5_override_micro_discontinuities_threshold_ms");this.J=U>0?U:10}unload(){this.W!=null&&(this.C.removeEventListener("sabrCaptionsDataLoaded",this.W),this.W=null);this.Ky=[];this.K=null;this.U=[];this.C.hQ("sabrCaptionsBufferedRangesUpdated",this.Ky)}X(U){return{formatId:g.Uu(U.info.Te.info,this.oS),B$:U.info.B$+(this.oS?0:1),startTimeMs:U.info.U*
1E3,durationMs:U.info.N*1E3}}};var FdB=class extends dU{constructor(U,O){super(O);this.W=U;this.C=O;this.logger=new g.Kr("caps");this.V=this.A=null;this.Y=new XcQ(this.C,this,this.logger,this.W.oS)}N(U,O,r){this.U();O=U.getId();O=O!=null&&O in this.W.K?this.W.K[O]:null;O||(O=U.languageCode,O=this.W.isManifestless?KyM(this,O,"386"):KyM(this,O));O&&(this.V=U,this.A=O,FyL(this.Y,r),this.C.hQ("sabrCaptionsTrackChanged",g.Uu(O.info,this.W.oS)))}J(U){var O=this.W.isManifestless?JYk(this,"386"):JYk(this);for(const r of O)p9(this.K,r);
U.kz()}U(){this.V&&(this.V=this.A=null,this.Y.unload(),this.C.hQ("sabrCaptionsTrackChanged",null))}B(){return""}};var z9L="WEBVTT".split("").map(U=>U.charCodeAt(0)),q9g=class extends uI{constructor(){super()}U(U,O){U instanceof ArrayBuffer&&(U=g.FB(new Uint8Array(U)));
const r=[];U=U.split(Tri);for(let P=1;P<U.length;P++){var V=U[P],D=O;if(V!==""&&!KdK.test(V)){var m=Gj.exec(V);if(m&&m.length>=4){var S=q0(m[1]),E=q0(m[2])-S;S+=D;var d=(m=m[3])?m.split(" "):[];m={};var L=null;var u="";var G=null,H="";for(const h of d){d=h.split(":");if(d.length!==2)continue;var l=d[1];switch(d[0]){case "line":d=l.split(",");d[0].endsWith("%")&&(L=d[0],m.kQ=Number.parseInt(L,10),d.length===2&&(u=d[1].trim()));break;case "position":d=l.split(",");G=d[0];m.xz=Number.parseInt(G,10);
d.length===2&&(H=d[1].trim());break;case "align":switch(l){case "start":m.textAlign=0;break;case "middle":m.textAlign=2;break;case "end":m.textAlign=1}}}L||u||(u="end");if(!G)switch(m.textAlign){case 0:m.xz=0;break;case 1:m.xz=100;break;case 2:m.xz=50}if(m.textAlign!=null){L=0;switch(u){case "center":L+=3;break;case "end":L+=6;break;default:L+=0}switch(H){case "line-left":L+=0;break;case "center":L+=1;break;case "line-right":L+=2;break;default:switch(m.textAlign){case 0:L+=0;break;case 2:L+=1;break;
case 1:L+=2}}u=L<0||L>8?7:L;m.Nc=u}V=V.substring(Gj.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");H=m;m=V;V={};if(m.indexOf("<")<0&&m.indexOf("&")<0)D=wCw(S,E,5,H),E=new XM(S,E,5,D.id,m,!1,g.yy(V)?void 0:V),r.push(D),r.push(E),D.K.push(E);else for(u=m.split(JuZ),u.length===1?(m=5,H=wCw(S,E,m,H)):(L=m=6,H=Object.assign({T5:32},H),H=new Tq(S,E,L,"_"+FM++,H)),r.push(H),L=S,G=0;G<u.length;G++)if(d=u[G],G%2===0){l=f9(`<html>${d}</html>`);let h;l.getElementsByTagName("parsererror").length?(h=l.createElement("span"),
h.appendChild(l.createTextNode(d))):h=l.firstChild;bii(this,L,E-(L-S),m,H,G>0,h,V,r)}else L=q0(d)+D}Gj.lastIndex=0}}return r}},KdK=/^NOTE/,Tri=/(?:\r\n|\r|\n){2,}/,Gj=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),JuZ=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var zNk=class extends g.f{constructor(U,O){super();this.C=U;this.D=O;this.K=null;this.VW=this.C.PB();this.logger=new g.Kr("caps")}clear(){this.K&&this.K.dispose();this.K=null}reset(){this.K&&this.K.reset()}UB(){super.UB();this.clear()}};var Ue3={windowColor:"#080808",windowOpacity:0,textAlign:2,Nc:7,xz:50,kQ:100,isDefault:!0,R2:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},s1M={windowColor:"#080808",windowOpacity:0,textAlign:0,Nc:7,xz:50,kQ:100,isDefault:!0,R2:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.mS("captions",class extends g.yn{constructor(U){super(U);this.C=U;this.m3=[];this.Fe={};this.OB={};this.V=!1;this.U="NONE";this.K=this.G=this.Y=this.f7=this.If=null;this.dH={kz:()=>{this.kz()},
df:(V,D,m,S,E=0)=>{const d=Number(this.videoData.S().C7().K.L7(g.VvY)??0);E>0&&d>0&&this.videoData.lengthSeconds>0&&E/this.videoData.lengthSeconds>d?this.C.O("tts",{dropcap:E}):this.df(V,D,m,S)}};
this.SJ=this.W=null;this.D=this.C.S();this.videoData=this.C.getVideoData();this.TH=this.C.wH();this.X={R2:{}};this.B={R2:{}};g.y7(this.videoData)?this.U="OFFLINE":g.X12(this.videoData,this.C)?this.U="HLS":TLi(this.videoData,this.C)?this.U="SABR_LIVE":g.F$Z(this.videoData,this.C)?this.U="LIVE":this.videoData.captionTracks.length?this.U="INNERTUBE":this.videoData.PE&&(this.U="TTS");this.lk=this.D.controlsType==="3";this.tQ=new zNk(this.C,this.D);this.W$=new g.se(this);this.N=new g.fG({L:"div",p7:"ytp-caption-window-container",
xX:{id:"ytp-caption-window-container"}});this.A={top:0,right:0,bottom:0,left:0,width:1,height:1};let O=null;const r=g.jy("yt-html5-player-modules::subtitlesModuleData");r&&(O=new g.rw(r));this.storage=O;this.c$=!!U.dL()?.qQ();this.J=BLB(this);this.Xe=!this.J&&this.lk&&this.c$&&(this.U==="LIVE"||this.U==="SABR_LIVE");g.Q(this,this.tQ);this.J?this.qQ=this.Vn=null:(this.Vn=new g.Ij(this.aS,void 0,this),g.Q(this,this.Vn),this.qQ=new g.Xq(this.TN,2E3,this),g.Q(this,this.qQ));g.Q(this,this.W$);g.lR(this.player,
this.N.element,4);g.Q(this,this.N);this.J||this.W$.K7(U,"resize",this.sB);(this.xl=g.aL(this.D)&&!g.cV()&&!this.C.isFullscreen()&&!this.J&&!this.Xe)&&this.W$.K7(U,"resize",this.t$);this.W$.K7(U,"onPlaybackAudioChange",this.jg);this.W$.K7(U,g.az("captions"),V=>{this.onCueRangeEnter(V)});
this.W$.K7(U,g.oz("captions"),V=>{this.onCueRangeExit(V)});
v8(this,ht()||{});g.kN(this.player,"onCaptionsModuleAvailable");this.U==="HLS"&&this.J&&(U=this.C.dL().Ed(),this.c$&&this.W$.K7(U.textTracks,"addtrack",this.Sg))}UB(){if(this.J||this.Xe){const U=this.C.dL();U&&!U.NQ()&&U.G()}else YV(this,!1);super.UB()}dT(){if(this.lk)return this.J||this.Xe;if(this.U==="HLS")return this.J;var U=this.getAudioTrack();if(VMZ(this)){if(!U.captionTracks.length)return!1;if(!this.K)return!0}U=ZB(U,g.Uv(this.D));return U==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:U==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?
sr(this):B8(this)||sr(this)?!0:ru2(this)}load(){super.load();this.G=this.getAudioTrack();if(this.K)this.W&&(this.tQ.clear(),this.J?Dek(this,!0):this.player.getPresentingPlayerType()!==3&&this.K.N(this.W,"json3",this.dH),this.U!=="HLS"&&this.J||this.Xe||Un(this)||g.kN(this.player,"captionschanged",eX(this.W)));else{if(this.U==="OFFLINE")var U=new NrL(this.player,this.videoData,this.getAudioTrack());else this.U==="SABR_LIVE"?U=new FdB(this.videoData.K,this.player):this.U==="HLS"?U=new iDT(this.player):
this.U==="LIVE"?U=new xeM(this.videoData.K,this.player):this.U==="INNERTUBE"?U=new tML(this.player,this.videoData,this.getAudioTrack()):(U=this.videoData,U=new P0Y(this.player,this.videoData.PE,this.videoData.videoId,U.captionsLanguagePreference||U.r9.captionsLanguagePreference||g.lu(U,"yt:cc_default_lang")||U.r9.c$,this.videoData.e1,this.videoData.eventId));this.K=U;g.Q(this,this.K);this.K.J(this.dH)}}unload(){this.J&&this.W?Dek(this,!1):(this.qQ&&this.qQ.Vr(),this.player.VA("captions"),this.m3=
[],this.K&&this.K.U(),this.tQ.clear(),this.Y&&this.player.H6(this.Y),this.sB());super.unload();this.player.wS();g.kN(this.player,"captionschanged",{})}create(){this.dT()&&this.load();var U;a:{if(this.D.Z("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(U=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(const O of U)if(O.kind==="asr"&&O.languageCode==="en"){U=
!0;break a}U=!1}U&&this.C.hQ("showpromotooltip",this.N.element)}kz(){var U=ZB(this.player.getAudioTrack(),g.Uv(this.D));var O=U==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?gU(this,this.V):U==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&sr(this)?On(this):B8(this)||this.V||ru2(this)?gU(this,this.V):sr(this)?On(this):null;if(this.U!=="HLS"&&this.J||this.Xe){const r=this.K.K.K(!0);U=[];for(let V=0;V<r.length;V++){const D=r[V],m=g.VD("TRACK");m.setAttribute("kind","subtitles");m.setAttribute("label",g.tB(D));m.setAttribute("srclang",
g.Wu(D));m.setAttribute("id",D.toString());this.Xe||m.setAttribute("src",this.K.B(D,"vtt"));D===O&&m.setAttribute("default","1");U.push(m)}O=this.C.dL();O.Fe(U);U=O.Ed();this.c$&&this.W$.K7(U.textTracks,"change",this.BE)}else!this.W&&O&&ST(this,O),g.kN(this.player,"onCaptionsTrackListChanged"),g.Cy(this.player,"onApiChange")}getTrackById(U){const O=this.K.K.K(!0);for(let r=0;r<O.length;r++)if(O[r].toString()===U)return O[r];return null}BE(){const U=this.C.dL().Ed().textTracks;let O=null;for(let r=
0;r<U.length;r++)U[r].mode==="showing"&&(O=this.getTrackById(U[r].id));(this.loaded?this.W:null)!==O&&ST(this,O,!0)}Sg(){this.K?.J(this.dH)}K_(){!this.W&&this.J||this.unload()}df(U,O,r,V){if(U){mQ(this,this.W??void 0);this.K.Xe()&&(this.m3=[],this.C.VA("captions"),$V(this.Vn),this.tQ.reset());a:{var D=this.tQ;V=V||0;r=Cm2(D,U,r||0);U=[];try{for(const a of r){const X=a.trackData,T=a.tO,J=D.D.Z("safari_live_drm_captions_fix");if(typeof X!=="string"){r=U;var m=r.concat;if(J&&Mbi(X))var S=vs3(D,X,T);
else{var E=D,d=O,L=X,u=T,G=V;if(!Q1i(L))throw Error("Invalid binary caption track data");E.K||(E.K=new aGg(G,d));S=E.K.U(L,u)}var H=m.call(r,S)}else{if(X.substring(0,6)==="WEBVTT")var l=U.concat(vs3(D,X,T));else{r=U;var P=r.concat;b:{d=D;E=O;if(X[0]==="{")try{d.K||(d.K=new neT(Y9T(E)));var h=d.K.U(X,T);break b}catch(dM){g.k(dM);h=[];break b}const Oi=f9(X);if(!Oi||!Oi.firstChild){const dM=Error("Invalid caption track data");dM.params=X;throw dM;}if(Oi.firstChild.tagName==="timedtext"){if(Number(Oi.firstChild.getAttribute("format"))===
3){L=Oi;d.K||(d.K=new Q4M(Y9T(E)));h=d.K.U(L,T);break b}const dM=Error("Unsupported subtitles format in web player (Format2)");dM.params=X;throw dM;}if(Oi.firstChild.tagName==="transcript"){const dM=Error("Unsupported subtitles format in web player (Format1)");dM.params=X;throw dM;}const HB=Error("Invalid caption track data");HB.params=X;throw HB;}l=P.call(r,h)}H=l}U=H}var n=U;break a}catch(a){g.JF(D.logger,187101178,`Captions parsing failed: ${a.message}. `);D.clear();n=[];break a}n=void 0}this.D.Z("html5_sabr_live_support_subfragmented_captions")&&
this.K instanceof FdB&&(O=this.K.Y,D=[],n.length>0&&(D=n.slice(O.U.length)),O.U=!O.K||O.K.info.Bh?[]:n,n=D);n.length>0&&(O=this.W,this.kF(O,!!O,Un(this)?"g":this.V?"m":"s"));this.player.H6(n,void 0,this.U==="LIVE"||this.U==="SABR_LIVE");!this.V||this.Xe||Un(this)||g.qI(this.D)||g.zu(this.D)||g.oL(this.D)||this.D.G==="shortspage"||this.player.isInline()||(this.qQ.Vr(),n=$aM({Nc:0,xz:5,kQ:5,l3:2,textAlign:0,qm:0,lang:"en"}),this.f7=[n],O=["Click "," for settings"],this.If||(D=new g.JFB({L:"svg",xX:{height:"100%",
version:"1.1",viewBox:"0 0 36 36",width:"100%"},JQ:[{L:"path",xI:!0,xX:{d:"m 23.94,18.78 c .03,-0.25 .05,-0.51 .05,-0.78 0,-0.27 -0.02,-0.52 -0.05,-0.78 l 1.68,-1.32 c .15,-0.12 .19,-0.33 .09,-0.51 l -1.6,-2.76 c -0.09,-0.17 -0.31,-0.24 -0.48,-0.17 l -1.99,.8 c -0.41,-0.32 -0.86,-0.58 -1.35,-0.78 l -0.30,-2.12 c -0.02,-0.19 -0.19,-0.33 -0.39,-0.33 l -3.2,0 c -0.2,0 -0.36,.14 -0.39,.33 l -0.30,2.12 c -0.48,.2 -0.93,.47 -1.35,.78 l -1.99,-0.8 c -0.18,-0.07 -0.39,0 -0.48,.17 l -1.6,2.76 c -0.10,.17 -0.05,.39 .09,.51 l 1.68,1.32 c -0.03,.25 -0.05,.52 -0.05,.78 0,.26 .02,.52 .05,.78 l -1.68,1.32 c -0.15,.12 -0.19,.33 -0.09,.51 l 1.6,2.76 c .09,.17 .31,.24 .48,.17 l 1.99,-0.8 c .41,.32 .86,.58 1.35,.78 l .30,2.12 c .02,.19 .19,.33 .39,.33 l 3.2,0 c .2,0 .36,-0.14 .39,-0.33 l .30,-2.12 c .48,-0.2 .93,-0.47 1.35,-0.78 l 1.99,.8 c .18,.07 .39,0 .48,-0.17 l 1.6,-2.76 c .09,-0.17 .05,-0.39 -0.09,-0.51 l -1.68,-1.32 0,0 z m -5.94,2.01 c -1.54,0 -2.8,-1.25 -2.8,-2.8 0,-1.54 1.25,-2.8 2.8,-2.8 1.54,0 2.8,1.25 2.8,2.8 0,1.54 -1.25,2.8 -2.8,2.8 l 0,0 z",
fill:"#fff"}}]}),g.Q(this,D),this.If=D.element),D=n.end-n.start,(H=g.tB(this.W))&&this.f7.push(new XM(n.start,D,0,n.id,H)),this.f7.push(new XM(n.start,D,0,n.id,O[0]),new XM(n.start,D,0,n.id,this.If,!0),new XM(n.start,D,0,n.id,O[1],!0)),this.player.H6(this.f7),this.qQ.ux());!this.V||this.Xe||Un(this)||(this.D.Z("enable_player_captions_persistence_state_machine")?rU(this,!0):g.Uv(this.D)?VG(this,!0):Dm(this,!0),this.G&&(this.G.J=this.W),this.player.wS());this.V=!1}}onCueRangeEnter(U){this.m3.push(U);
$V(this.Vn)}onCueRangeExit(U){g.Cu(this.m3,U);this.K instanceof xeM&&this.K.A&&this.player.uc([U]);$V(this.Vn)}getCaptionWindowContainerId(){return this.N.element.id}TN(){ODZ(this,this.f7);this.f7=null}aS(){if(!this.xl||!this.J){this.Vn.stop();g.ne(this.OB);this.m3.sort(g.Iz);var U=this.m3;if(this.Y){const O=g.of(U,function(r){return this.Y.indexOf(r)===-1},this);
O.length&&(U=O)}for(const O of U)O instanceof Tq?Eew(this,O):deZ(this,O);for(const [O,r]of Object.entries(this.Fe)){const V=O,D=r;this.OB[V]?(D.element.parentNode||(D instanceof GII||D instanceof uHQ||g.Pt(this.Fe,(m,S)=>{S!==V&&m.U.params.Nc===D.U.params.Nc&&m.U.params.xz===D.U.params.xz&&m.U.params.kQ===D.U.params.kQ&&(m.dispose(),delete this.Fe[S]);return S===V},this),this.N.element.appendChild(D.element)),D.Y(this.OB[V])):(D.dispose(),delete this.Fe[V])}}}FA(){v8(this,{},!0);
g.kN(this.player,"captionssettingschanged")}lW(){var U=this.D.Z("enable_player_captions_new_style_defaults")?s1M:Ue3,O=U.R2;U={background:O.background,backgroundOpacity:O.backgroundOpacity,charEdgeStyle:O.charEdgeStyle,color:O.color,fontFamily:O.fontFamily,fontSizeIncrement:O.fontSizeIncrement,fontStyle:O.bold&&O.italic?3:O.bold?1:O.italic?2:0,textOpacity:O.textOpacity,windowColor:U.windowColor,windowOpacity:U.windowOpacity};O=ht()||{};O.background!=null&&(U.background=O.background);O.backgroundOverride!=
null&&(U.backgroundOverride=O.backgroundOverride);O.backgroundOpacity!=null&&(U.backgroundOpacity=O.backgroundOpacity);O.backgroundOpacityOverride!=null&&(U.backgroundOpacityOverride=O.backgroundOpacityOverride);O.charEdgeStyle!=null&&(U.charEdgeStyle=O.charEdgeStyle);O.charEdgeStyleOverride!=null&&(U.charEdgeStyleOverride=O.charEdgeStyleOverride);O.color!=null&&(U.color=O.color);O.colorOverride!=null&&(U.colorOverride=O.colorOverride);O.fontFamily!=null&&(U.fontFamily=O.fontFamily);O.fontFamilyOverride!=
null&&(U.fontFamilyOverride=O.fontFamilyOverride);O.fontSizeIncrement!=null&&(U.fontSizeIncrement=O.fontSizeIncrement);O.fontSizeIncrementOverride!=null&&(U.fontSizeIncrementOverride=O.fontSizeIncrementOverride);O.fontStyle!=null&&(U.fontStyle=O.fontStyle);O.fontStyleOverride!=null&&(U.fontStyleOverride=O.fontStyleOverride);O.textOpacity!=null&&(U.textOpacity=O.textOpacity);O.textOpacityOverride!=null&&(U.textOpacityOverride=O.textOpacityOverride);O.windowColor!=null&&(U.windowColor=O.windowColor);
O.windowColorOverride!=null&&(U.windowColorOverride=O.windowColorOverride);O.windowOpacity!=null&&(U.windowOpacity=O.windowOpacity);O.windowOpacityOverride!=null&&(U.windowOpacityOverride=O.windowOpacityOverride);return U}hh(U,O){const r={};Object.assign(r,ht());Object.assign(r,U);v8(this,r,O);g.kN(this.player,"captionssettingschanged")}sB(){!this.J&&this.loaded&&(g.Wt(this.Fe,function(U,O){U.dispose();delete this.Fe[O]},this),this.aS())}bu(U,O){switch(U){case "fontSize":if(isNaN(O))break;
U=g.u4(O,-2,4);this.hh({fontSizeIncrement:U});return U;case "reload":O&&!this.J&&ST(this,this.W,!0);break;case "stickyLoading":O!==void 0&&this.D.N&&(this.D.Z("enable_player_captions_persistence_state_machine")?rU(this,!(!O||!O.userInitiated)):g.Uv(this.D)?VG(this,!!O):Dm(this,!!O));break;case "track":return HDL(this,O);case "tracklist":return this.K?g.XD(this.K.K.K(!(!O||!O.includeAsr)),r=>eX(r)):[];
case "translationLanguages":return this.K?this.K.G.map(r=>Object.assign({},r)):[];
case "sampleSubtitles":this.J||O===void 0||YV(this,!!O);break;case "sampleSubtitlesCustomized":this.J||YV(this,!!O,O);break;case "recommendedTranslationLanguages":return g.qU();case "defaultTranslationSourceTrackIndices":return this.K?this.K.Fe:[]}}getOptions(){const U="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.D.N&&U.push("stickyLoading");return U}wF(){let U=this.W;if(this.C.n4("captions")){if(this.D.Z("html5_modify_caption_vss_logging"))return(U=this.videoData.MZ??
null)?{cc:g.RX(U)}:{};if(U){let O=U.vssId;U.translationLanguage&&O&&(O=`t${O}.${g.Wu(U)}`);return{cc:O}}}return{}}y0(U){this.isSubtitlesOn()?(this.D.Z("enable_player_captions_persistence_state_machine")&&U?rU(this,!1):g.Uv(this.D)?VG(this,!1):Dm(this,!1),mQ(this),ST(this,null,!0)):this.eN(U)}eN(U){const O=Un(this)||!this.W?gU(this,!0):this.W;O&&this.ev(O.vssId,"m");this.isSubtitlesOn()||ST(this,O,this.D.Z("enable_player_captions_persistence_state_machine")?U:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.W&&!Un(this)}jg(){const U=Un(this);sr(this,U)?ST(this,this.getAudioTrack().K,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),VMZ(this)&&(this.V=!1,this.W=null,this.K&&(this.K.dispose(),this.K=null)),this.dT()&&(U?ST(this,gU(this,!1),!1):this.load()))}oJ(U){if(this.D.experiments.yn("web_enable_captions_set_target_container")&&U!==this.SJ){var O=this.N.element;O.parentNode&&g.Ec(O);(this.SJ=U)?(this.SJ.appendChild(O),O.style.position="absolute",O.style.bottom="0",O.style.left=
"0",O.style.width="100%",O.style.height="auto",O.style.top="auto"):(g.lR(this.player,O,4),O.style.position="absolute",O.style.bottom="auto",O.style.left="0",O.style.width="100%",O.style.height="100%",O.style.top="0");this.sB()}}i8(U){U&&(this.A={top:U.top,right:U.right,bottom:U.bottom,left:U.left,width:1-U.left-U.right,height:1-U.top-U.bottom},this.N.element.style.top=`${this.A.top*100}%`,this.N.element.style.left=`${this.A.left*100}%`,this.N.element.style.width=`${this.A.width*100}%`,this.N.element.style.height=
`${this.A.height*100}%`,this.N.element.style.position="absolute",U=LdZ(this))&&(this.N.element.style.width=`${U.width}px`,this.N.element.style.height=`${U.height}px`)}onVideoDataChange(U,O){U==="newdata"&&(this.videoData=O,this.loaded&&this.unload(),this.V=!1,this.W=null,this.K&&(this.K.dispose(),this.K=null,g.kN(this.player,"captionschanged",{})),this.dT()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}t$(){const U=this.C.dL();U&&!U.NQ()&&U.G();this.C.isFullscreen()?(this.J=this.lk=
!0,this.loaded&&this.kz()):(this.lk=this.D.controlsType==="3",this.J=BLB(this));ST(this,this.W)}AQ(){const U=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;U&&g.bu(this.player,"innertubeCommand",U)}kF(U,O,r){const V=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm;let D="";U&&(D=U.vssId,D=D.replace(V,""));let m="";U&&U.getId()&&(m=U.getId()||"");U&&U.getXtags()&&(U=U.getXtags(),U=U.replace(V,""),m=m.concat(`;${U}`));this.U==="HLS"&&(m="");this.C.kF(O?D:"",O?m:
"",r)}ev(U,O){U=(U||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");U.length>0&&this.C.ev(U,O)}});})(_yt_player);
